-- Migration 019 — management-accounts actuals (store × nominal × month) (Phase 16)
-- Store-level P&L actuals uploaded from the management-accounts workbook, same
-- grain as finance.forecast_line so the two compose: actuals take precedence for
-- any month they cover, the forecast carries the forward months, and the frozen
-- forecast serves as budget.
-- Additive and idempotent. Safe to re-run.
--
-- ROLLBACK: DROP TABLE IF EXISTS finance.mgmt_actual;

BEGIN;

CREATE TABLE IF NOT EXISTS finance.mgmt_actual (
  actual_id    bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  scope        varchar(20)  NOT NULL DEFAULT 'STORES',
  entity       varchar(120),
  unit         varchar(120),           -- store
  line_label   varchar(160) NOT NULL,  -- nominal
  ym           char(7)      NOT NULL,  -- YYYY-MM
  value        numeric      NOT NULL DEFAULT 0,
  source       varchar(120),
  updated_by   varchar(160),
  updated_at   timestamptz  NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- One value per store × nominal × month (upsert grain).
CREATE UNIQUE INDEX IF NOT EXISTS ux_mgmt_actual_grain
  ON finance.mgmt_actual (scope, COALESCE(unit, ''), line_label, ym);
CREATE INDEX IF NOT EXISTS ix_mgmt_actual_ym ON finance.mgmt_actual (ym);
CREATE INDEX IF NOT EXISTS ix_mgmt_actual_unit ON finance.mgmt_actual (scope, unit);

COMMIT;
