-- Migration 020 — Joiin consolidated P&L, full account detail (Phase 17)
-- The live Joiin connection loads the consolidated P&L by nominal, monthly,
-- with intercompany eliminations applied. This is the detailed companion to the
-- summary rows in finance.fact_financials (source_system 'JOIIN'), which keep
-- driving the existing dashboards. Refreshed from a Claude session via the Joiin
-- MCP connector. Additive and idempotent.
--
-- ROLLBACK: DROP TABLE IF EXISTS finance.joiin_pl;

BEGIN;

CREATE TABLE IF NOT EXISTS finance.joiin_pl (
  joiin_pl_id  bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  section      varchar(40)  NOT NULL,   -- Revenue / Cost of Sales / Expenses / Other Income / Other Expenses
  account      varchar(180) NOT NULL,   -- the nominal as reported by Joiin
  ym           char(7)      NOT NULL,   -- YYYY-MM
  value        numeric      NOT NULL DEFAULT 0,
  currency     char(3)      NOT NULL DEFAULT 'GBP',
  elimination  varchar(20)  NOT NULL DEFAULT 'eliminate',
  source       varchar(120) NOT NULL DEFAULT 'JOIIN',
  updated_by   varchar(160),
  updated_at   timestamptz  NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- One value per section × account × month (upsert grain).
CREATE UNIQUE INDEX IF NOT EXISTS ux_joiin_pl_grain
  ON finance.joiin_pl (section, account, ym);
CREATE INDEX IF NOT EXISTS ix_joiin_pl_ym ON finance.joiin_pl (ym);

COMMIT;
