-- Migration 021 — Joiin per-entity standalone P&L (Phase 18)
-- The Joiin connector's by-company report gives each group company's own
-- (un-eliminated) P&L. This is the companion to finance.joiin_pl (the eliminated
-- group consolidation) and drives the board-pack P&L formats and per-entity
-- drill-down in Management Accounts. Refreshed from a Claude session via the
-- Joiin MCP connector. Additive and idempotent.
--
-- ROLLBACK: DROP TABLE IF EXISTS finance.joiin_pl_entity;

BEGIN;

CREATE TABLE IF NOT EXISTS finance.joiin_pl_entity (
  joiin_pl_entity_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  entity_id    varchar(64)  NOT NULL,   -- Joiin company id
  entity_name  varchar(160) NOT NULL,   -- legal entity name as held in Joiin
  section      varchar(40)  NOT NULL,   -- Revenue / Cost of Sales / Expenses / Other Income / Other Expenses
  account      varchar(180) NOT NULL,   -- the nominal as reported by Joiin
  ym           char(7)      NOT NULL,   -- YYYY-MM
  value        numeric      NOT NULL DEFAULT 0,
  currency     char(3)      NOT NULL DEFAULT 'GBP',
  source       varchar(120) NOT NULL DEFAULT 'JOIIN',
  updated_by   varchar(160),
  updated_at   timestamptz  NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- One value per entity × section × account × month (upsert grain).
CREATE UNIQUE INDEX IF NOT EXISTS ux_joiin_pl_entity_grain
  ON finance.joiin_pl_entity (entity_id, section, account, ym);
CREATE INDEX IF NOT EXISTS ix_joiin_pl_entity_ym ON finance.joiin_pl_entity (ym);
CREATE INDEX IF NOT EXISTS ix_joiin_pl_entity_ent ON finance.joiin_pl_entity (entity_id);

COMMIT;
