-- Migration 022 — governed P&L board-pack formats (Phase 19)
-- Moves the board-pack P&L layouts out of code and into the database so Finance
-- owns them under GOVERN. One row per scope kind (store / head_office /
-- franchise / consolidated); `spec` is the ordered layout (sections, sub-bands,
-- account lines mapping chart-of-accounts nominals, subtotals, and derived
-- rows). The pure renderer reads this spec. Additive and idempotent.
--
-- ROLLBACK: DROP TABLE IF EXISTS finance.pl_format;

BEGIN;

CREATE TABLE IF NOT EXISTS finance.pl_format (
  pl_format_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  scope_kind   varchar(30)  NOT NULL,   -- store / head_office / franchise / consolidated
  name         varchar(120) NOT NULL,
  spec         jsonb        NOT NULL,    -- ordered array of layout entries
  version      integer      NOT NULL DEFAULT 1,
  is_active    boolean      NOT NULL DEFAULT true,
  updated_by   varchar(160),
  updated_at   timestamptz  NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- One active format per scope kind (the editable current layout).
CREATE UNIQUE INDEX IF NOT EXISTS ux_pl_format_scope ON finance.pl_format (scope_kind);

COMMIT;
