-- Migration 023 — Joiin board-pack P&L output (Phase 22)
-- Stores each Joiin Custom Report (board pack) exactly as Joiin lays it out:
-- ordered rows per scope × month, with the section/line/subtotal/computed/pct
-- structure preserved. This is the authoritative Management Accounts view —
-- Joiin computes the layout and the intercompany wholesale elimination, so the
-- app renders it verbatim. Refreshed via the Joiin custom-report endpoint.
-- Additive and idempotent.
--
-- ROLLBACK: DROP TABLE IF EXISTS finance.joiin_boardpack;

BEGIN;

CREATE TABLE IF NOT EXISTS finance.joiin_boardpack (
  joiin_boardpack_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  scope       varchar(30)  NOT NULL,   -- store / head_office / franchise / consolidated
  ym          char(7)      NOT NULL,   -- YYYY-MM
  seq         integer      NOT NULL,   -- row order within the board pack
  kind        varchar(12)  NOT NULL,   -- section / line / total / computed / pct
  label       varchar(200) NOT NULL,
  value       numeric,                 -- money, or a fraction for pct rows; null for section headers
  updated_by  varchar(160),
  updated_at  timestamptz  NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- One row per scope × month × position.
CREATE UNIQUE INDEX IF NOT EXISTS ux_joiin_boardpack_grain
  ON finance.joiin_boardpack (scope, ym, seq);
CREATE INDEX IF NOT EXISTS ix_joiin_boardpack_scope_ym ON finance.joiin_boardpack (scope, ym);

COMMIT;
