-- Migration 025 — SKU Analysis Dashboard report store (Phase 25)
-- Stores the computed tables ingested from the distributed SKU analysis
-- workbooks (Top 80 / Bottom 20, and later Dormant), one row per sheet line,
-- so the dashboard renders the same analysis the decks show and refreshes by
-- re-uploading each period's workbook. Additive and idempotent.
--
-- ROLLBACK: DROP TABLE IF EXISTS finance.sku_analysis;

BEGIN;

CREATE TABLE IF NOT EXISTS finance.sku_analysis (
  sku_analysis_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  report_kind varchar(20)  NOT NULL,   -- 'top80' | 'dormant'
  sheet_key   varchar(40)  NOT NULL,   -- 'meta' | 'exec' | 'top80_store' | 'bottom20_store' | 'licence' | 'zero_sellers' | ...
  seq         integer      NOT NULL,   -- row order within the sheet
  data        jsonb        NOT NULL,   -- the row as an object
  updated_by  varchar(160),
  updated_at  timestamptz  NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE UNIQUE INDEX IF NOT EXISTS ux_sku_analysis_grain
  ON finance.sku_analysis (report_kind, sheet_key, seq);
CREATE INDEX IF NOT EXISTS ix_sku_analysis_kind ON finance.sku_analysis (report_kind);

COMMIT;
