-- Migration 026 — Business Projects register (Plan — HO, Phase 28)
-- A self-contained register of cross-functional business change projects owned
-- outside finance (head-office planning). Additive and idempotent.
--
-- ROLLBACK: DROP TABLE IF EXISTS finance.business_project;

BEGIN;

CREATE TABLE IF NOT EXISTS finance.business_project (
  business_project_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name        varchar(200) NOT NULL,
  category    varchar(80),
  owner       varchar(120),
  status      varchar(20)  NOT NULL DEFAULT 'Planned',   -- Planned / Active / On hold / Done
  rag         varchar(10)  NOT NULL DEFAULT 'green',      -- green / amber / red
  target_ym   char(7),                                    -- YYYY-MM target completion
  budget      numeric,                                    -- £ budget
  notes       text,
  created_by  varchar(160),
  updated_by  varchar(160),
  created_at  timestamptz  NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at  timestamptz  NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS ix_business_project_status ON finance.business_project (status);

COMMIT;
