-- Migration 028 — forecast & budget versions (Phase 29, Tier 1 item 7)
-- Turns the single live forecast (finance.forecast_line) into something that can
-- be captured, named, locked and compared. A version is a frozen snapshot of the
-- forecast lines at a point in time, classified as a BUDGET (the approved annual
-- plan) or a FORECAST (a periodic re-forecast). The working forecast keeps
-- evolving; versions do not change once taken. Additive and idempotent.
--
-- ROLLBACK (run only if reverting this migration):
--   DROP TABLE IF EXISTS finance.forecast_version_line;
--   DROP TABLE IF EXISTS finance.forecast_version;

BEGIN;

CREATE TABLE IF NOT EXISTS finance.forecast_version (
  version_id   bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  label        varchar(120) NOT NULL,                 -- e.g. 'FY26 Budget', 'Q3 Reforecast'
  kind         varchar(10)  NOT NULL CHECK (kind IN ('BUDGET','FORECAST')),
  status       varchar(10)  NOT NULL DEFAULT 'DRAFT' CHECK (status IN ('DRAFT','APPROVED','ARCHIVED')),
  fiscal_year  char(4),                               -- the year it pertains to, YYYY (optional)
  notes        text,
  line_count   integer      NOT NULL DEFAULT 0,        -- rows captured (denormalised for the list)
  created_by   varchar(160),
  created_at   timestamptz  NOT NULL DEFAULT CURRENT_TIMESTAMP,
  approved_by  varchar(160),
  approved_at  timestamptz,
  archived_at  timestamptz
);

CREATE INDEX IF NOT EXISTS ix_forecast_version_kind ON finance.forecast_version (kind, status);

-- The frozen snapshot lines — same grain as finance.forecast_line.
CREATE TABLE IF NOT EXISTS finance.forecast_version_line (
  id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  version_id  bigint       NOT NULL REFERENCES finance.forecast_version(version_id) ON DELETE CASCADE,
  scope       varchar(12)  NOT NULL,
  unit        varchar(120),
  entity      varchar(120),
  line_label  varchar(160) NOT NULL,
  cost_type   varchar(14)  NOT NULL,
  ym          varchar(7),
  value       numeric(20,6) NOT NULL
);

CREATE INDEX IF NOT EXISTS ix_forecast_version_line_version ON finance.forecast_version_line (version_id);

COMMIT;
