-- Migration 029 — two-step sign-in (TOTP MFA), opt-in (Phase 29, Tier 1 item 3)
-- Per-user TOTP secret (encrypted at rest) plus one-time recovery codes. MFA is
-- never forced: a row exists only for users who chose to enrol, and `enabled` is
-- true only once they have confirmed a code. Additive and idempotent.
--
-- ROLLBACK (run only if reverting this migration):
--   DROP TABLE IF EXISTS governance.mfa_recovery_code;
--   DROP TABLE IF EXISTS governance.user_mfa;

BEGIN;

CREATE TABLE IF NOT EXISTS governance.user_mfa (
  user_id         integer     PRIMARY KEY REFERENCES public.users(id) ON DELETE CASCADE,
  secret_enc      text        NOT NULL,               -- AES-256-GCM(base32 secret)
  enabled         boolean     NOT NULL DEFAULT false,  -- true only after a confirmed code
  last_step       bigint,                              -- highest accepted TOTP step (replay guard)
  failed_attempts integer     NOT NULL DEFAULT 0,      -- consecutive failed verifications
  locked_until    timestamptz,                         -- verification lockout window
  confirmed_at    timestamptz,
  created_at      timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at      timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS governance.mfa_recovery_code (
  id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id     integer     NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
  code_hash   text        NOT NULL,                    -- bcrypt(recovery code)
  used_at     timestamptz,                             -- single-use: set when redeemed
  created_at  timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS ix_mfa_recovery_user ON governance.mfa_recovery_code (user_id);

COMMIT;
