-- Migration 036 — Joiin consolidated Balance Sheet (Tier 3.2, three-statement)
-- The second statement. Joiin's Connect API exposes a balance-sheet report
-- alongside the P&L; this stores the consolidated (eliminated) balance sheet by
-- nominal, as-at each month end, mirroring finance.joiin_pl. With the P&L (net
-- result) and two consecutive balance sheets, lib/threestatement-rules.js
-- derives the indirect cash-flow statement — so the three statements link
-- without inventing any figures. Additive and idempotent.
--
-- Values are AS-AT balances (a position at month end), not movements — unlike
-- the P&L, which is a flow within the month.
--
-- ROLLBACK: DROP TABLE IF EXISTS finance.joiin_bs;

BEGIN;

CREATE TABLE IF NOT EXISTS finance.joiin_bs (
  joiin_bs_id  bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  section      varchar(60)  NOT NULL,   -- Fixed Assets / Current Assets / Current Liabilities / Equity, etc.
  account      varchar(180) NOT NULL,   -- the nominal as reported by Joiin
  ym           char(7)      NOT NULL,   -- YYYY-MM (position as at this month end)
  value        numeric      NOT NULL DEFAULT 0,
  currency     char(3)      NOT NULL DEFAULT 'GBP',
  elimination  varchar(20)  NOT NULL DEFAULT 'eliminate',
  source       varchar(120) NOT NULL DEFAULT 'JOIIN',
  updated_by   varchar(160),
  updated_at   timestamptz  NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- One value per section × account × month (upsert grain).
CREATE UNIQUE INDEX IF NOT EXISTS ux_joiin_bs_grain
  ON finance.joiin_bs (section, account, ym);
CREATE INDEX IF NOT EXISTS ix_joiin_bs_ym ON finance.joiin_bs (ym);

COMMIT;
