-- Migration 037 — Report Builder (Tier 3.3, self-serve reporting)
-- A saved report is a named binding of a dataset to parameters (period / month
-- / year). The layout language, the renderer and the Excel/PDF export path all
-- already exist (lib/pl-format.js, lib/ma-export-rules.js); this table just lets
-- a user save and re-run a report without an engineer building each one.
--
-- Unlike finance.pl_format (exactly one layout per fixed scope), report_def has
-- no fixed scope — many rows, each keyed by a free-form dataset_key. Additive
-- and idempotent.
--
-- ROLLBACK: DROP TABLE IF EXISTS finance.report_def;

BEGIN;

CREATE TABLE IF NOT EXISTS finance.report_def (
  report_id    bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name         varchar(120) NOT NULL,
  dataset_key  varchar(60)  NOT NULL,   -- e.g. consolidated-pnl / balance-sheet / management-accounts
  params       jsonb        NOT NULL DEFAULT '{}'::jsonb,  -- { period, month, year, ... }
  spec         jsonb,                   -- optional layout override (pl-format grammar); null = dataset default
  version      integer      NOT NULL DEFAULT 1,
  is_active    boolean      NOT NULL DEFAULT true,
  owner        varchar(160),
  updated_by   varchar(160),
  created_at   timestamptz  NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at   timestamptz  NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS ix_report_def_active ON finance.report_def (is_active, updated_at DESC);

COMMIT;
