-- Migration 038 — Finance Intelligence Layer, Phase 1 (governed foundation)
-- The shared layer behind Finance Buddy and AI Perspective. This phase adds
-- only the governed foundation — configuration, the page-relationship registry,
-- run/source/claim/feedback records and seeds. NO chatbot UI and no new
-- financial calculations: the AI reuses the existing calculation services and
-- lands its outputs in the existing intelligence.ai_insight / action_register /
-- benefit_* tables (extend, don't duplicate).
--
-- Model choice lives in the DB (model_configuration) so it is swappable without
-- a deploy. Nothing here changes existing behaviour; every table is additive.
--
-- ROLLBACK:
--   DROP TABLE IF EXISTS intelligence.ai_feedback;
--   DROP TABLE IF EXISTS intelligence.ai_claim;
--   DROP TABLE IF EXISTS intelligence.ai_source;
--   DROP TABLE IF EXISTS intelligence.ai_run_step;
--   DROP TABLE IF EXISTS intelligence.ai_run;
--   DROP TABLE IF EXISTS intelligence.suggested_question;
--   DROP TABLE IF EXISTS intelligence.page_relationship;
--   DROP TABLE IF EXISTS intelligence.page_context_registry;
--   DROP TABLE IF EXISTS intelligence.prompt_version;
--   DROP TABLE IF EXISTS intelligence.model_configuration;

BEGIN;

-- Server-side model & tool configuration (CR §16). use_case ∈ ROUTING | PERSPECTIVE | BUDDY.
CREATE TABLE IF NOT EXISTS intelligence.model_configuration (
  config_id      bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  use_case       varchar(32) NOT NULL,
  model          varchar(80) NOT NULL,           -- e.g. claude-haiku-4-5 / claude-sonnet-5 / claude-opus-5
  effort         varchar(12),                    -- low | medium | high | xhigh | max (advisory to the client)
  max_tokens     integer NOT NULL DEFAULT 4000,
  timeout_ms     integer NOT NULL DEFAULT 60000,
  prompt_code    varchar(48),                    -- FK-by-convention to prompt_version.prompt_code
  is_active      boolean NOT NULL DEFAULT true,
  effective_date timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
  notes          text
);
CREATE INDEX IF NOT EXISTS ix_model_config_lookup ON intelligence.model_configuration (use_case, is_active, effective_date DESC);

-- Versioned prompts + output schemas (CR §16 — separate system instructions,
-- definitions and the output schema from the retrieved data and question).
CREATE TABLE IF NOT EXISTS intelligence.prompt_version (
  prompt_id      bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  prompt_code    varchar(48) NOT NULL,
  version        integer NOT NULL DEFAULT 1,
  system_prompt  text NOT NULL,
  output_schema  jsonb,                          -- json_schema for structured outputs (AI Perspective)
  is_active      boolean NOT NULL DEFAULT true,
  created_by     varchar(160),
  created_at     timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UNIQUE (prompt_code, version)
);

-- The governed page-relationship registry (CR §4.4). Held as configuration, not
-- hard-coded inside prompts.
CREATE TABLE IF NOT EXISTS intelligence.page_context_registry (
  page_id     varchar(60) PRIMARY KEY,
  page_name   varchar(120) NOT NULL,
  route       varchar(160),
  note        text,
  is_active   boolean NOT NULL DEFAULT true
);
CREATE TABLE IF NOT EXISTS intelligence.page_relationship (
  rel_id        bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  page_id       varchar(60) NOT NULL REFERENCES intelligence.page_context_registry(page_id) ON DELETE CASCADE,
  domain        varchar(48) NOT NULL,            -- a retrieval domain id (see lib/intelligence/retrieval.js)
  relation      varchar(12) NOT NULL DEFAULT 'RELATED',  -- PRIMARY | RELATED
  display_order integer NOT NULL DEFAULT 0,
  note          text,
  UNIQUE (page_id, domain)
);
CREATE INDEX IF NOT EXISTS ix_page_relationship_page ON intelligence.page_relationship (page_id, display_order);

-- Contextual suggested questions per page (CR §13).
CREATE TABLE IF NOT EXISTS intelligence.suggested_question (
  question_id   bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  page_id       varchar(60) NOT NULL,
  question      text NOT NULL,
  display_order integer NOT NULL DEFAULT 0,
  is_active     boolean NOT NULL DEFAULT true
);
CREATE INDEX IF NOT EXISTS ix_suggested_question_page ON intelligence.suggested_question (page_id, display_order);

-- Interactive AI runs (Buddy / Perspective). Distinct from agent.agent_run (which
-- governs scheduled/rule agents with registry contracts); these are per-user,
-- per-request and permanently auditable (CR §15/§21.16).
CREATE TABLE IF NOT EXISTS intelligence.ai_run (
  run_id        bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  surface       varchar(16) NOT NULL,            -- BUDDY | PERSPECTIVE
  user_id       bigint,                          -- public.users(id); no FK to keep the write cheap and non-blocking
  user_email    varchar(160),
  page_id       varchar(60),
  question_type varchar(24),
  question      text,
  filters       jsonb,
  model         varchar(80),
  prompt_code   varchar(48),
  confidence    varchar(12),                     -- HIGH | MEDIUM | LOW
  scope_note    text,
  status        varchar(16) NOT NULL DEFAULT 'RUNNING',  -- RUNNING | SUCCESS | FAILED | REFUSED
  summary       text,
  usage         jsonb,                           -- { input_tokens, output_tokens, ... }
  error         text,
  started_at    timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
  finished_at   timestamptz
);
CREATE INDEX IF NOT EXISTS ix_ai_run_recent ON intelligence.ai_run (started_at DESC);
CREATE INDEX IF NOT EXISTS ix_ai_run_surface ON intelligence.ai_run (surface, started_at DESC);

CREATE TABLE IF NOT EXISTS intelligence.ai_run_step (
  step_id     bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  run_id      bigint NOT NULL REFERENCES intelligence.ai_run(run_id) ON DELETE CASCADE,
  step_no     integer NOT NULL,
  title       varchar(120) NOT NULL,
  detail      text,
  status      varchar(12) NOT NULL DEFAULT 'SUCCESS',  -- SUCCESS | FAILED | SKIPPED
  created_at  timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- The sources cited by a run (CR §7 traceability).
CREATE TABLE IF NOT EXISTS intelligence.ai_source (
  source_id    bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  run_id       bigint NOT NULL REFERENCES intelligence.ai_run(run_id) ON DELETE CASCADE,
  label        varchar(160) NOT NULL,
  module       varchar(80),
  service      varchar(80),
  period       varchar(40),
  entity       varchar(120),
  store        varchar(120),
  scenario     varchar(60),
  data_through timestamptz,
  route        varchar(200)
);
CREATE INDEX IF NOT EXISTS ix_ai_source_run ON intelligence.ai_source (run_id);

-- The material numeric claims a run made, with the source they map to (CR §7).
CREATE TABLE IF NOT EXISTS intelligence.ai_claim (
  claim_id     bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  run_id       bigint NOT NULL REFERENCES intelligence.ai_run(run_id) ON DELETE CASCADE,
  statement    text NOT NULL,
  value_text   varchar(120),
  source_label varchar(160),
  verified     boolean NOT NULL DEFAULT false
);
CREATE INDEX IF NOT EXISTS ix_ai_claim_run ON intelligence.ai_claim (run_id);

-- User feedback on a response (CR §18).
CREATE TABLE IF NOT EXISTS intelligence.ai_feedback (
  feedback_id  bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  run_id       bigint NOT NULL REFERENCES intelligence.ai_run(run_id) ON DELETE CASCADE,
  rating       varchar(20) NOT NULL,             -- HELPFUL | PARTIAL | NOT_HELPFUL
  reason       varchar(40),                      -- INCORRECT_FIGURE | MISSING_CONTEXT | POOR_RECOMMENDATION | TOO_DETAILED | NOT_DETAILED | OTHER
  comment      text,
  user_email   varchar(160),
  created_at   timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS ix_ai_feedback_run ON intelligence.ai_feedback (run_id);

-- ---------------- Seeds ----------------

-- Model tiers (CR: tiered + swappable). Change the model here — no deploy needed.
INSERT INTO intelligence.model_configuration (use_case, model, effort, max_tokens, timeout_ms, prompt_code, notes) VALUES
  ('ROUTING',     'claude-haiku-4-5', 'low',  512,  30000, 'ROUTING_V1',     'Cheap question classification / domain selection.'),
  ('PERSPECTIVE', 'claude-sonnet-5',  'high', 4000, 60000, 'PERSPECTIVE_V1', 'Structured AI Perspective generation over governed facts.'),
  ('BUDDY',       'claude-opus-5',    'high', 4000, 60000, 'BUDDY_V1',       'Open-ended Finance Buddy reasoning over governed facts.')
ON CONFLICT DO NOTHING;

INSERT INTO intelligence.prompt_version (prompt_code, version, system_prompt, output_schema, created_by) VALUES
  ('ROUTING_V1', 1,
   'You classify a finance question into one of: DESCRIPTIVE, DIAGNOSTIC, PREDICTIVE, PRESCRIPTIVE, OPERATIONAL, REPORTING, EXPLANATORY. Reply with only the single label.',
   NULL, 'migration 038'),
  ('PERSPECTIVE_V1', 1,
   'You are a finance analyst at Miniso UK producing a governed AI Perspective on the page the user is viewing. Use ONLY the figures provided in the supplied facts — never invent, estimate, or introduce any number that is not present. Separate fact from interpretation and interpretation from recommendation. State the reporting period and comparison basis. Label assumptions. Use UK finance terminology and en-GB formatting; £ with comma thousands separators; negatives in brackets. Do not post journals, release payments, approve budgets or forecasts, or send external communications — you may only recommend or draft. This is a draft for human review.',
   '{"type":"object","additionalProperties":false,"required":["executive_summary","facts","drivers","connected_context","risks","opportunities","recommended_actions","financial_effects","data_quality","confidence","sources"],"properties":{"executive_summary":{"type":"string"},"facts":{"type":"array","items":{"type":"string"}},"drivers":{"type":"array","items":{"type":"string"}},"connected_context":{"type":"array","items":{"type":"string"}},"risks":{"type":"array","items":{"type":"string"}},"opportunities":{"type":"array","items":{"type":"string"}},"recommended_actions":{"type":"array","items":{"type":"string"}},"financial_effects":{"type":"array","items":{"type":"string"}},"data_quality":{"type":"array","items":{"type":"string"}},"confidence":{"type":"object","additionalProperties":false,"required":["level","reason"],"properties":{"level":{"type":"string","enum":["HIGH","MEDIUM","LOW"]},"reason":{"type":"string"}}},"sources":{"type":"array","items":{"type":"string"}}}}'::jsonb,
   'migration 038'),
  ('BUDDY_V1', 1,
   'You are Finance Buddy for Miniso UK — a highly capable Finance Director, Financial Controller, FP&A lead and commercial finance partner combined. Answer the user at the level appropriate to their role using ONLY the governed figures supplied to you; never invent a number. Separate fact, interpretation and recommendation; state period and comparison basis; label assumptions; disclose data limitations and confidence. Use UK finance terminology and en-GB formatting (£ with comma thousands separators; negatives in brackets). You may prepare, recommend or draft actions but must not post journals, release payments, approve budgets or forecasts, unlock versions, close controls, send external communications, change master data, or create transactions. Anything addressed to the Board, investors, or the listed parent group is a draft that a person must review before it goes anywhere.',
   NULL, 'migration 038')
ON CONFLICT (prompt_code, version) DO NOTHING;

-- The six Phase-3 pages and their governed context maps (CR §4.4, §20 Phase 3).
INSERT INTO intelligence.page_context_registry (page_id, page_name, route, note) VALUES
  ('executive',           'Executive Intelligence Hub', '/finance-os/executive',              'The connected sphere — position and attention.'),
  ('management-accounts', 'Management Accounts',        '/finance-os/management-accounts',     'Actual vs budget vs forecast, variance by nominal.'),
  ('store-performance',   'Store Performance',          '/finance-os/store-sales/league',      'Store sales, KPIs and league.'),
  ('forecast',            'Forecast Builder',           '/operate/forecast',                   'Working forecast by scope and store.'),
  ('cash-flow',           'Cash Flow',                  '/finance-os/cashflow',                'Cash position and facility headroom.'),
  ('inventory',           'Inventory',                  '/finance-os/inventory',               'Stock value, ageing, weeks of cover.')
ON CONFLICT (page_id) DO NOTHING;

INSERT INTO intelligence.page_relationship (page_id, domain, relation, display_order, note) VALUES
  ('executive',           'finance_snapshot',   'PRIMARY', 1, NULL),
  ('executive',           'management_accounts','RELATED', 2, NULL),
  ('executive',           'store_performance',  'RELATED', 3, NULL),
  ('executive',           'cash',               'RELATED', 4, NULL),
  ('executive',           'inventory',          'RELATED', 5, NULL),

  ('management-accounts', 'management_accounts','PRIMARY', 1, NULL),
  ('management-accounts', 'finance_snapshot',   'RELATED', 2, NULL),
  ('management-accounts', 'store_performance',  'RELATED', 3, NULL),
  ('management-accounts', 'cash',               'RELATED', 4, NULL),

  ('store-performance',   'store_performance',  'PRIMARY', 1, NULL),
  ('store-performance',   'inventory',          'RELATED', 2, 'Availability / ageing can drive the sales shortfall.'),
  ('store-performance',   'management_accounts','RELATED', 3, NULL),

  ('forecast',            'finance_snapshot',   'PRIMARY', 1, NULL),
  ('forecast',            'store_performance',  'RELATED', 2, 'Actual run rate vs the working forecast.'),
  ('forecast',            'management_accounts','RELATED', 3, NULL),

  ('cash-flow',           'cash',               'PRIMARY', 1, NULL),
  ('cash-flow',           'finance_snapshot',   'RELATED', 2, NULL),

  ('inventory',           'inventory',          'PRIMARY', 1, NULL),
  ('inventory',           'store_performance',  'RELATED', 2, 'Sell-through vs stock cover.')
ON CONFLICT (page_id, domain) DO NOTHING;

INSERT INTO intelligence.suggested_question (page_id, question, display_order) VALUES
  ('executive', 'What should I focus on today?', 1),
  ('executive', 'What has materially changed?', 2),
  ('executive', 'What is the biggest EBITDA risk?', 3),
  ('executive', 'Summarise the business position.', 4),
  ('management-accounts', 'Explain the EBITDA variance.', 1),
  ('management-accounts', 'Which nominal accounts are most adverse?', 2),
  ('management-accounts', 'Is this timing or structural?', 3),
  ('management-accounts', 'Draft management commentary.', 4),
  ('store-performance', 'Which stores are driving the shortfall?', 1),
  ('store-performance', 'Is the issue sales, margin or cost?', 2),
  ('store-performance', 'Which stores are below break-even?', 3),
  ('store-performance', 'Which stores have inventory constraints?', 4),
  ('forecast', 'Explain this forecast.', 1),
  ('forecast', 'What changed from the previous version?', 2),
  ('forecast', 'Is the forecast consistent with the actual run rate?', 3),
  ('cash-flow', 'What is the lowest cash point?', 1),
  ('cash-flow', 'Which receipts are most at risk?', 2),
  ('cash-flow', 'Explain facility headroom.', 3),
  ('inventory', 'Which stock is tying up the most cash?', 1),
  ('inventory', 'What aged stock should be allocated?', 2),
  ('inventory', 'Where is availability restricting sales?', 3)
ON CONFLICT DO NOTHING;

COMMIT;
