-- Migration 039 — Finance Intelligence Layer, Phase 2 (Finance Buddy MVP)
-- Adds conversation memory for the interactive Finance Buddy: a conversation is
-- a titled thread of user/assistant turns for one signed-in user, and each
-- assistant turn links back to the governed intelligence.ai_run that produced
-- it (so sources, claims, confidence and audit stay in the Phase 1 record — we
-- do NOT duplicate them here). Everything is additive and idempotent.
--
-- No new financial calculations: Buddy still interprets governed facts the
-- existing services produce, through the shared orchestrator. This migration
-- only adds where the conversation is remembered.
--
-- ROLLBACK:
--   ALTER TABLE intelligence.ai_run DROP COLUMN IF EXISTS conversation_id;
--   DROP TABLE IF EXISTS intelligence.buddy_message;
--   DROP TABLE IF EXISTS intelligence.buddy_conversation;

BEGIN;

-- A Buddy conversation thread. Owned by one user; short rolling metadata columns
-- (message_count / last_message_at) keep the history list cheap to render.
CREATE TABLE IF NOT EXISTS intelligence.buddy_conversation (
  conversation_id  bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id          bigint,                        -- public.users(id); no FK to keep writes cheap
  user_email       varchar(160),
  title            varchar(160) NOT NULL DEFAULT 'New conversation',
  message_count    integer NOT NULL DEFAULT 0,
  archived         boolean NOT NULL DEFAULT false,
  created_at       timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
  last_message_at  timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS ix_buddy_conv_user ON intelligence.buddy_conversation (user_email, archived, last_message_at DESC);

-- One turn in a conversation. Assistant turns carry the confidence label and a
-- denormalised copy of the cited sources (jsonb) so the thread renders without
-- re-running retrieval; the authoritative record remains intelligence.ai_run.
CREATE TABLE IF NOT EXISTS intelligence.buddy_message (
  message_id       bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  conversation_id  bigint NOT NULL REFERENCES intelligence.buddy_conversation(conversation_id) ON DELETE CASCADE,
  role             varchar(12) NOT NULL,          -- USER | ASSISTANT
  content          text NOT NULL,
  run_id           bigint REFERENCES intelligence.ai_run(run_id) ON DELETE SET NULL,
  confidence       varchar(12),                   -- HIGH | MEDIUM | LOW (assistant turns)
  question_type    varchar(24),
  sources          jsonb,                         -- [{ label, module, period, dataThrough, route }]
  refused          boolean NOT NULL DEFAULT false,
  created_at       timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS ix_buddy_msg_conv ON intelligence.buddy_message (conversation_id, created_at);

-- Link a governed run back to its conversation (nullable — AI Perspective runs
-- have no conversation). Additive column on the Phase 1 table.
ALTER TABLE intelligence.ai_run ADD COLUMN IF NOT EXISTS conversation_id bigint;
CREATE INDEX IF NOT EXISTS ix_ai_run_conversation ON intelligence.ai_run (conversation_id);

COMMIT;
