-- Migration 041 — Finance Intelligence Layer, Phase 5 (proactive briefings)
-- Adds the governed proactive-briefing surface: a scheduled brief generated over
-- governed facts (the same retrieval/orchestrator path as Buddy and Perspective),
-- stored auditable, and surfaced to finance/admin users in their Inbox.
--
-- Additive: one new table plus BRIEFING model config + prompt seeds. No new
-- financial calculations — the model still only interprets governed figures.
-- Every insert is idempotent (guarded), so the migration is safe to re-run.
--
-- ROLLBACK:
--   DROP TABLE IF EXISTS intelligence.briefing;
--   DELETE FROM intelligence.model_configuration WHERE use_case = 'BRIEFING';
--   DELETE FROM intelligence.prompt_version WHERE prompt_code = 'BRIEFING_V1';

BEGIN;

-- A generated briefing. body holds the structured brief (headline, summary,
-- highlights, watch_items, recommended_focus); the authoritative traceability
-- (sources, claims, usage) stays on intelligence.ai_run via run_id.
CREATE TABLE IF NOT EXISTS intelligence.briefing (
  briefing_id  bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  kind         varchar(32) NOT NULL DEFAULT 'EXEC',   -- EXEC | (future kinds)
  title        varchar(200) NOT NULL,
  headline     text,
  summary      text,
  body         jsonb,                                 -- full structured brief
  confidence   varchar(12),                           -- HIGH | MEDIUM | LOW
  run_id       bigint REFERENCES intelligence.ai_run(run_id) ON DELETE SET NULL,
  sources      jsonb,                                 -- denormalised cited sources for rendering
  created_by   varchar(160),                          -- 'briefing-cron' or an actor email
  created_at   timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS ix_briefing_recent ON intelligence.briefing (kind, created_at DESC);

-- Model tier for briefings (swappable without a deploy, like the others).
-- Guarded insert — model_configuration has no natural unique key.
INSERT INTO intelligence.model_configuration (use_case, model, effort, max_tokens, timeout_ms, prompt_code, notes)
SELECT 'BRIEFING', 'claude-sonnet-5', 'high', 3000, 60000, 'BRIEFING_V1',
       'Scheduled proactive finance briefing over governed facts.'
WHERE NOT EXISTS (SELECT 1 FROM intelligence.model_configuration WHERE use_case = 'BRIEFING');

-- Briefing prompt + output schema. prompt_version has UNIQUE (prompt_code, version).
INSERT INTO intelligence.prompt_version (prompt_code, version, system_prompt, output_schema, created_by) VALUES
  ('BRIEFING_V1', 1,
   'You are the Finance Intelligence briefing writer for Miniso UK, preparing a short proactive brief for the finance and leadership team. Use ONLY the governed figures supplied to you; never invent, estimate or introduce a number that is not present. Lead with what changed and what needs attention. Separate fact from interpretation; state the period and comparison basis; flag anything working/unapproved and any stale or missing data. Be concise and scannable. Use UK finance terminology and en-GB formatting (£ with comma thousands separators; negatives in brackets). You may highlight and recommend where to focus, but you do not take any action and anything Board/investor-facing is a draft for human review.',
   '{"type":"object","additionalProperties":false,"required":["headline","summary","highlights","watch_items","recommended_focus","confidence","sources"],"properties":{"headline":{"type":"string"},"summary":{"type":"string"},"highlights":{"type":"array","items":{"type":"string"}},"watch_items":{"type":"array","items":{"type":"string"}},"recommended_focus":{"type":"array","items":{"type":"string"}},"confidence":{"type":"object","additionalProperties":false,"required":["level","reason"],"properties":{"level":{"type":"string","enum":["HIGH","MEDIUM","LOW"]},"reason":{"type":"string"}}},"sources":{"type":"array","items":{"type":"string"}}}}'::jsonb,
   'migration 041')
ON CONFLICT (prompt_code, version) DO NOTHING;

COMMIT;
