-- Migration 042 — Finance Intelligence Layer, Phase 5b (drafted commentary)
-- A governed draft-and-sign-off surface: the model drafts narrative commentary
-- (management accounts, cash, trading, board pack) over governed facts; a human
-- approves or rejects before it is used. Board/investor material stays a draft
-- until sign-off. No new calculations — the model interprets governed figures.
--
-- Additive and idempotent (guarded inserts). Safe to re-run.
--
-- ROLLBACK:
--   DROP TABLE IF EXISTS intelligence.commentary;
--   DELETE FROM intelligence.model_configuration WHERE use_case = 'COMMENTARY';
--   DELETE FROM intelligence.prompt_version WHERE prompt_code = 'COMMENTARY_V1';

BEGIN;

-- A drafted piece of commentary and its sign-off state. draft holds the
-- structured narrative (sections + summary); traceability lives on ai_run.
CREATE TABLE IF NOT EXISTS intelligence.commentary (
  commentary_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  subject       varchar(32) NOT NULL,                 -- MANAGEMENT_ACCOUNTS | CASH | TRADING | BOARD
  scope_ref     varchar(120),                         -- optional entity/period label
  title         varchar(200) NOT NULL,
  draft         jsonb,                                 -- { sections:[{heading,body}], summary }
  confidence    varchar(12),                           -- HIGH | MEDIUM | LOW
  status        varchar(12) NOT NULL DEFAULT 'DRAFT'
                CHECK (status IN ('DRAFT','APPROVED','REJECTED')),
  run_id        bigint REFERENCES intelligence.ai_run(run_id) ON DELETE SET NULL,
  sources       jsonb,
  created_by    varchar(160),
  reviewed_by   varchar(160),
  reviewed_at   timestamptz,
  review_note   text,
  created_at    timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS ix_commentary_recent ON intelligence.commentary (subject, created_at DESC);
CREATE INDEX IF NOT EXISTS ix_commentary_status ON intelligence.commentary (status);

-- Model tier for commentary drafting (swappable without a deploy).
INSERT INTO intelligence.model_configuration (use_case, model, effort, max_tokens, timeout_ms, prompt_code, notes)
SELECT 'COMMENTARY', 'claude-sonnet-5', 'high', 3500, 60000, 'COMMENTARY_V1',
       'Drafts governed narrative commentary for human sign-off.'
WHERE NOT EXISTS (SELECT 1 FROM intelligence.model_configuration WHERE use_case = 'COMMENTARY');

INSERT INTO intelligence.prompt_version (prompt_code, version, system_prompt, output_schema, created_by) VALUES
  ('COMMENTARY_V1', 1,
   'You are drafting finance commentary for Miniso UK for a human reviewer to check and sign off. Use ONLY the governed figures supplied; never invent, estimate or introduce a number that is not present. Write clear, structured narrative in short sections: explain what the figures show, what changed versus the comparison basis, the drivers evident in the data, and what to watch. Distinguish fact from interpretation. State the period and basis. Flag anything working/unapproved and any stale or missing data. Use UK finance terminology and en-GB formatting (£ with comma thousands separators; negatives in brackets). This is a DRAFT for human sign-off, not a final or published statement; anything Board/investor-facing must be reviewed by a person before use. You do not take any action.',
   '{"type":"object","additionalProperties":false,"required":["title","sections","summary","confidence","sources"],"properties":{"title":{"type":"string"},"sections":{"type":"array","items":{"type":"object","additionalProperties":false,"required":["heading","body"],"properties":{"heading":{"type":"string"},"body":{"type":"string"}}}},"summary":{"type":"string"},"confidence":{"type":"object","additionalProperties":false,"required":["level","reason"],"properties":{"level":{"type":"string","enum":["HIGH","MEDIUM","LOW"]},"reason":{"type":"string"}}},"sources":{"type":"array","items":{"type":"string"}}}}'::jsonb,
   'migration 042')
ON CONFLICT (prompt_code, version) DO NOTHING;

COMMIT;
