-- Migration 044 — Email invites & self-service password set-up
-- Turns user onboarding from "admin types a password and tells them out of band"
-- into a proper invite flow: the admin creates the account, an email goes out
-- with a one-time link, and the user sets their own password before first login.
-- The same mechanism backs an emailed "reset password" link.
--
-- Two additive pieces:
--   1. public.users.must_change_password — marks an account that has been
--      invited but has not yet had a password set by its owner (so the admin
--      list can show "invited, pending first sign-in").
--   2. governance.user_invite — one-time tokens. Only the SHA-256 hash of the
--      token is stored; the raw token lives only in the emailed link, exactly
--      like a password reset. A token has a purpose (INVITE | RESET), an expiry
--      and a used_at stamp; it is single-use.
--
-- Additive and idempotent (guarded). Safe to re-run.
--
-- ROLLBACK:
--   DROP TABLE IF EXISTS governance.user_invite;
--   ALTER TABLE public.users DROP COLUMN IF EXISTS must_change_password;

BEGIN;

ALTER TABLE public.users
  ADD COLUMN IF NOT EXISTS must_change_password boolean NOT NULL DEFAULT false;

-- One-time invite / password-reset tokens. token_hash is sha256(raw) in hex;
-- the raw token is never stored. A row is spent when used_at is set.
CREATE TABLE IF NOT EXISTS governance.user_invite (
  invite_id   bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id     integer NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
  token_hash  text NOT NULL,
  purpose     varchar(16) NOT NULL DEFAULT 'INVITE'
              CHECK (purpose IN ('INVITE','RESET')),
  expires_at  timestamptz NOT NULL,
  used_at     timestamptz,
  created_by  varchar(160),
  created_at  timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- Token lookup on redemption is by hash; make it unique so a hash resolves to
-- at most one row.
CREATE UNIQUE INDEX IF NOT EXISTS ux_user_invite_token ON governance.user_invite (token_hash);
-- Find a user's still-open invites cheaply (used to supersede old ones).
CREATE INDEX IF NOT EXISTS ix_user_invite_open ON governance.user_invite (user_id) WHERE used_at IS NULL;

COMMIT;
