-- Migration 045 — Corporate Reporting Centre (HOME)
-- One governed Corporate Reporting Engine, not five isolated generators. A
-- report is a template-derived instance → ordered sections (each a "page") →
-- components (KPI / table / chart / commentary / action …). Every figure stays
-- traceable to a governed Finance OS source adapter; AI commentary reuses the
-- Finance Intelligence Layer (migration 038/042) and stays a DRAFT until a human
-- signs it off. Approved report versions are frozen snapshots that never change
-- when the underlying data moves.
--
-- Additive and idempotent (IF NOT EXISTS, guarded inserts). Safe to re-run.
--
-- ROLLBACK:
--   DROP TABLE IF EXISTS finance.report_export;
--   DROP TABLE IF EXISTS finance.report_version;
--   DROP TABLE IF EXISTS finance.report_component;
--   DROP TABLE IF EXISTS finance.report_section_instance;
--   DROP TABLE IF EXISTS finance.report_instance;
--   DROP TABLE IF EXISTS finance.report_schedule;
--   DROP TABLE IF EXISTS finance.report_template_section;
--   DROP TABLE IF EXISTS finance.report_template;
--   DELETE FROM intelligence.model_configuration WHERE use_case = 'REPORT_COMMENTARY';
--   DELETE FROM intelligence.prompt_version WHERE prompt_code = 'REPORT_COMMENTARY_V1';

BEGIN;

-- ---------------------------------------------------------------------------
-- Templates — the official, reusable report definitions. Corporate templates
-- are the company standard; team/personal variants are layered in the rules.
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS finance.report_template (
  template_id            bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  template_key           varchar(48) NOT NULL UNIQUE,      -- WEEKLY_TRADE_PACK …
  name                   varchar(160) NOT NULL,
  purpose                text,
  audience               varchar(240),
  frequency              varchar(40),                      -- Weekly | Monthly | …
  default_owner_role     varchar(32) DEFAULT 'FINANCE',
  classification         varchar(12) NOT NULL DEFAULT 'CORPORATE'
                         CHECK (classification IN ('CORPORATE','TEAM','PERSONAL')),
  default_confidentiality varchar(16) NOT NULL DEFAULT 'INTERNAL'
                         CHECK (default_confidentiality IN ('PUBLIC','INTERNAL','CONFIDENTIAL','BOARD','RESTRICTED')),
  default_ai             jsonb DEFAULT '[]'::jsonb,         -- default perspective keys
  is_active              boolean NOT NULL DEFAULT true,
  effective_date         date,
  created_by             varchar(160),
  created_at             timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at             timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- Template sections — the default ordered structure of each template.
CREATE TABLE IF NOT EXISTS finance.report_template_section (
  section_id             bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  template_id            bigint NOT NULL REFERENCES finance.report_template(template_id) ON DELETE CASCADE,
  section_key            varchar(48) NOT NULL,
  title                  varchar(160) NOT NULL,
  purpose                text,
  position               int NOT NULL DEFAULT 0,
  mandatory              boolean NOT NULL DEFAULT false,
  default_source_key     varchar(48),                       -- reporting source adapter
  default_ai_perspective varchar(32),
  default_page_type      varchar(32) DEFAULT 'content',
  default_layout         varchar(32) DEFAULT 'standard',
  created_at             timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UNIQUE (template_id, section_key)
);
CREATE INDEX IF NOT EXISTS ix_report_tsection_tpl ON finance.report_template_section (template_id, position);

-- ---------------------------------------------------------------------------
-- Report instances — a specific report for a period/scope, with its lifecycle.
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS finance.report_instance (
  report_id              bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  template_id            bigint REFERENCES finance.report_template(template_id) ON DELETE SET NULL,
  template_key           varchar(48),                       -- denormalised for listing
  title                  varchar(200) NOT NULL,
  reporting_period       varchar(40),                       -- e.g. '2026-W30' | '2026-06'
  data_through_date      date,
  comparator             varchar(24),                       -- BUDGET | LATEST_FORECAST | PRIOR_YEAR | …
  forecast_version       varchar(120),
  budget_version         varchar(120),
  scenario               varchar(60),
  currency               varchar(8) DEFAULT 'GBP',
  display_units          varchar(12) DEFAULT 'GBP',          -- GBP | GBP_000 | GBP_M
  scope                  jsonb DEFAULT '{}'::jsonb,          -- { entities:[], stores:[], departments:[], franchises:[] }
  audience               varchar(240),
  owner                  varchar(160),
  reviewer               varchar(160),
  approver               varchar(160),
  expected_issue_date    date,
  confidentiality        varchar(16) NOT NULL DEFAULT 'INTERNAL'
                         CHECK (confidentiality IN ('PUBLIC','INTERNAL','CONFIDENTIAL','BOARD','RESTRICTED')),
  status                 varchar(20) NOT NULL DEFAULT 'DRAFT'
                         CHECK (status IN ('DRAFT','DATA_PENDING','COMMENTARY_PENDING','REVIEW_READY',
                                           'IN_REVIEW','RETURNED','APPROVAL_READY','APPROVED','ISSUED',
                                           'SUPERSEDED','ARCHIVED','CANCELLED')),
  version_seq            int NOT NULL DEFAULT 0,             -- latest issued version sequence
  version_label          varchar(24) DEFAULT 'Draft v0.1',
  issue_date             date,
  created_by             varchar(160),
  created_at             timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at             timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS ix_report_instance_recent ON finance.report_instance (created_at DESC);
CREATE INDEX IF NOT EXISTS ix_report_instance_status ON finance.report_instance (status);
CREATE INDEX IF NOT EXISTS ix_report_instance_owner  ON finance.report_instance (owner);

-- Section instances — the ordered sections of one report. In this release a
-- section IS a page (1:1); page_type/layout carry the presentation intent so
-- the page layer can grow later without a schema change.
CREATE TABLE IF NOT EXISTS finance.report_section_instance (
  section_inst_id        bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  report_id              bigint NOT NULL REFERENCES finance.report_instance(report_id) ON DELETE CASCADE,
  template_section_id    bigint REFERENCES finance.report_template_section(section_id) ON DELETE SET NULL,
  section_key            varchar(48) NOT NULL,
  title                  varchar(160) NOT NULL,
  purpose                text,
  position               int NOT NULL DEFAULT 0,
  included               boolean NOT NULL DEFAULT true,
  page_type              varchar(32) DEFAULT 'content',
  layout                 varchar(32) DEFAULT 'standard',
  filters                jsonb DEFAULT '{}'::jsonb,
  source_key             varchar(48),
  ai_perspective         varchar(32),
  data_status            varchar(16) DEFAULT 'PENDING',      -- PENDING | READY | PARTIAL | MISSING
  commentary_status      varchar(16) DEFAULT 'NONE',         -- NONE | DRAFT | REVIEWED | APPROVED | REJECTED
  approval_status        varchar(16) DEFAULT 'PENDING',
  created_at             timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at             timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS ix_report_section_report ON finance.report_section_instance (report_id, position);

-- Components — the atoms rendered on a section/page. A "commentary" component
-- carries its own draft→sign-off state and a link to the auditable AI run.
CREATE TABLE IF NOT EXISTS finance.report_component (
  component_id           bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  report_id              bigint NOT NULL REFERENCES finance.report_instance(report_id) ON DELETE CASCADE,
  section_inst_id        bigint NOT NULL REFERENCES finance.report_section_instance(section_inst_id) ON DELETE CASCADE,
  component_type         varchar(24) NOT NULL
                         CHECK (component_type IN ('cover','contents','exec_summary','kpi_row','kpi',
                                                   'table','chart','commentary','action','risk_opp',
                                                   'decision','appendix','text','source_footer')),
  title                  varchar(160),
  position               int NOT NULL DEFAULT 0,
  source_key             varchar(48),                        -- reporting source adapter key
  filters                jsonb DEFAULT '{}'::jsonb,
  config                 jsonb DEFAULT '{}'::jsonb,          -- display settings, chart type, static text …
  -- AI commentary fields (component_type = 'commentary')
  ai_perspective         varchar(32),
  ai_status              varchar(12) DEFAULT 'NONE'
                         CHECK (ai_status IN ('NONE','DRAFT','REVIEWED','APPROVED','REJECTED')),
  ai_run_id              bigint REFERENCES intelligence.ai_run(run_id) ON DELETE SET NULL,
  ai_model               varchar(48),
  ai_prompt_code         varchar(48),
  ai_confidence          varchar(12),
  ai_data_through        date,
  ai_sources             jsonb,
  draft_text             text,                               -- original AI output (retained)
  approved_text          text,                               -- final approved wording
  reviewed_by            varchar(160),
  reviewed_at            timestamptz,
  created_at             timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at             timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS ix_report_component_section ON finance.report_component (section_inst_id, position);
CREATE INDEX IF NOT EXISTS ix_report_component_report  ON finance.report_component (report_id);

-- ---------------------------------------------------------------------------
-- Versions — a frozen snapshot of the whole assembled report. An approved
-- version is locked; it never changes when the underlying data moves.
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS finance.report_version (
  version_id             bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  report_id              bigint NOT NULL REFERENCES finance.report_instance(report_id) ON DELETE CASCADE,
  seq                    int NOT NULL,
  label                  varchar(24) NOT NULL,               -- 'Draft v0.2' | 'Approved v1.0'
  snapshot               jsonb NOT NULL,                     -- fully resolved report (figures + approved commentary + sources)
  status                 varchar(20) NOT NULL,               -- report status at snapshot
  change_summary         text,
  locked                 boolean NOT NULL DEFAULT false,
  created_by             varchar(160),
  created_at             timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UNIQUE (report_id, seq)
);
CREATE INDEX IF NOT EXISTS ix_report_version_report ON finance.report_version (report_id, seq DESC);

-- Exports — a record of every generated artifact (never a screenshot source).
CREATE TABLE IF NOT EXISTS finance.report_export (
  export_id              bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  report_id              bigint NOT NULL REFERENCES finance.report_instance(report_id) ON DELETE CASCADE,
  version_id             bigint REFERENCES finance.report_version(version_id) ON DELETE SET NULL,
  format                 varchar(8) NOT NULL CHECK (format IN ('PPTX','PDF','XLSX')),
  checksum               varchar(80),
  byte_size              int,
  watermark              varchar(48),
  confidentiality        varchar(16),
  exported_by            varchar(160),
  created_at             timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS ix_report_export_report ON finance.report_export (report_id, created_at DESC);

-- Schedules — recurring report cadence. The system may auto-create a DRAFT; it
-- must never auto-issue an unreviewed report.
CREATE TABLE IF NOT EXISTS finance.report_schedule (
  schedule_id            bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  template_key           varchar(48) NOT NULL,
  name                   varchar(160),
  frequency              varchar(40),
  cadence_note           varchar(240),
  owner                  varchar(160),
  reviewer               varchar(160),
  approver               varchar(160),
  next_due               date,
  data_cutoff_rule       varchar(120),
  issue_deadline_rule    varchar(120),
  recipients             jsonb DEFAULT '[]'::jsonb,
  reminder_rule          varchar(120),
  auto_generate          boolean NOT NULL DEFAULT false,
  is_active              boolean NOT NULL DEFAULT true,
  created_by             varchar(160),
  created_at             timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at             timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS ix_report_schedule_due ON finance.report_schedule (next_due) WHERE is_active;

-- ---------------------------------------------------------------------------
-- Seed the five corporate templates (visible as cards from day one).
-- ---------------------------------------------------------------------------
INSERT INTO finance.report_template (template_key, name, purpose, audience, frequency, default_confidentiality, default_ai, effective_date, created_by)
VALUES
 ('WEEKLY_TRADE_PACK', 'Weekly Trade Pack',
  'Weekly review of trading, store performance, margin, inventory and commercial actions.',
  'CEO, COO, Finance, Retail and Commercial leadership.', 'Weekly', 'INTERNAL',
  '["EXECUTIVE","COMMERCIAL_FINANCE","RISK","OPPORTUNITY","ACTION"]'::jsonb, CURRENT_DATE, 'migration 045'),
 ('MANAGEMENT_ACCOUNTING_REPORT', 'Management Accounting Report',
  'Monthly financial performance report following month-end close.',
  'CEO, COO, Finance Director, Senior Leadership Team, Department owners.', 'Monthly', 'CONFIDENTIAL',
  '["FINANCE_DIRECTOR","FINANCIAL_CONTROLLER","FPA","CASH_TREASURY","RISK","ACTION"]'::jsonb, CURRENT_DATE, 'migration 045'),
 ('FINANCE_BOARD_DECK', 'Finance Board Deck',
  'Strategic, decision-focused finance report for the Board.',
  'Board, Shareholders, CEO, COO, Finance Director.', 'Monthly or quarterly', 'BOARD',
  '["FINANCE_DIRECTOR","EXECUTIVE","RISK","OPPORTUNITY","CASH_TREASURY","ACTION"]'::jsonb, CURRENT_DATE, 'migration 045'),
 ('BUDGET_FORECASTS_DECK', 'Budget & Forecasts Deck',
  'Explain the annual budget, latest forecast, scenarios and key assumptions.',
  'Board, CEO, COO, Finance, Budget owners, Department heads.', 'Annual + each reforecast', 'CONFIDENTIAL',
  '["FPA","FINANCE_DIRECTOR","COMMERCIAL_FINANCE","CASH_TREASURY","RISK","OPPORTUNITY"]'::jsonb, CURRENT_DATE, 'migration 045'),
 ('FRANCHISE_DECK', 'Franchise Deck',
  'Complete view of franchise trading, financial performance, receivables, pipeline and risk.',
  'CEO, COO, Finance Director, Franchise & Commercial leadership, Operations.', 'Monthly', 'CONFIDENTIAL',
  '["EXECUTIVE","COMMERCIAL_FINANCE","FINANCE_DIRECTOR","RISK","CASH_TREASURY","ACTION"]'::jsonb, CURRENT_DATE, 'migration 045')
ON CONFLICT (template_key) DO NOTHING;

-- Weekly Trade Pack sections (the template wired end-to-end this release).
INSERT INTO finance.report_template_section (template_id, section_key, title, position, mandatory, default_source_key, default_ai_perspective, default_page_type)
SELECT t.template_id, s.section_key, s.title, s.position, s.mandatory, s.src, s.persp, s.ptype
FROM finance.report_template t
CROSS JOIN (VALUES
  ('cover',            'Cover Page',                          1,  true,  NULL,                NULL,               'cover'),
  ('exec_summary',     'Executive Trade Summary',             2,  true,  'executive_hub',     'EXECUTIVE',        'exec_summary'),
  ('company_sales',    'Company Sales Performance',           3,  true,  'store_sales',       'COMMERCIAL_FINANCE','content'),
  ('sales_vs_plan',    'Sales versus Budget and Forecast',    4,  false, 'management_accounts','FPA',             'content'),
  ('lfl',              'Like-for-Like Performance',           5,  false, 'store_sales',       'COMMERCIAL_FINANCE','content'),
  ('store_ranking',    'Store Ranking',                       6,  false, 'store_ranking',     NULL,               'content'),
  ('store_exceptions', 'Store Exceptions',                    7,  false, 'store_ranking',     'RISK',             'content'),
  ('margin',           'Gross Margin and Absolute Margin',    8,  false, 'management_accounts','COMMERCIAL_FINANCE','content'),
  ('trading_kpis',     'Transactions, ATV, Units and UPT',    9,  false, 'store_sales',       NULL,               'content'),
  ('inventory_avail',  'Inventory Availability',              10, false, 'inventory',         'OPERATIONAL',      'content'),
  ('inventory_age',    'Inventory Ageing and Cover',          11, false, 'inventory',         'RISK',             'content'),
  ('product',          'Product or SKU Performance',          12, false, 'sku',               'COMMERCIAL_FINANCE','content'),
  ('franchise',        'Franchise Trading',                   13, false, 'franchise',         NULL,               'content'),
  ('new_stores',       'New Store Performance',               14, false, 'store_ranking',     NULL,               'content'),
  ('risk_opp',         'Commercial Risks and Opportunities',  15, false, 'executive_hub',     'RISK',             'risk_opp'),
  ('actions',          'Priority Actions',                    16, true,  'actions',           'ACTION',           'action'),
  ('appendix',         'Appendix',                            17, false, NULL,                NULL,               'appendix')
) AS s(section_key, title, position, mandatory, src, persp, ptype)
WHERE t.template_key = 'WEEKLY_TRADE_PACK'
ON CONFLICT (template_id, section_key) DO NOTHING;

-- Management Accounting Report sections.
INSERT INTO finance.report_template_section (template_id, section_key, title, position, mandatory, default_source_key, default_ai_perspective, default_page_type)
SELECT t.template_id, s.section_key, s.title, s.position, s.mandatory, s.src, s.persp, s.ptype
FROM finance.report_template t
CROSS JOIN (VALUES
  ('cover',           'Cover Page',                        1,  true,  NULL,                 NULL,                 'cover'),
  ('exec_summary',    'Executive Financial Summary',       2,  true,  'executive_hub',      'FINANCE_DIRECTOR',   'exec_summary'),
  ('close_status',    'Month-End Status and Data Quality', 3,  false, 'close',              'FINANCIAL_CONTROLLER','content'),
  ('pnl',             'Consolidated P&L',                  4,  true,  'management_accounts','FINANCIAL_CONTROLLER','content'),
  ('revenue',         'Revenue',                           5,  false, 'management_accounts','FPA',                'content'),
  ('margin',          'Gross Margin',                      6,  false, 'management_accounts','COMMERCIAL_FINANCE', 'content'),
  ('ebitda',          'EBITDA',                            7,  false, 'management_accounts','FINANCE_DIRECTOR',   'content'),
  ('opcosts',         'Operating Costs',                   8,  false, 'management_accounts','FINANCIAL_CONTROLLER','content'),
  ('cashflow',        'Cash Flow',                         9,  false, 'cash',               'CASH_TREASURY',      'content'),
  ('working_capital', 'Working Capital',                   10, false, 'cash',               'CASH_TREASURY',      'content'),
  ('inventory',       'Inventory',                         11, false, 'inventory',          'OPERATIONAL',        'content'),
  ('forecast',        'Forecast Update',                   12, false, 'forecast',           'FPA',                'content'),
  ('risk_action',     'Risks, Opportunities and Actions',  13, false, 'actions',            'RISK',               'risk_opp'),
  ('decisions',       'Decisions Required',                14, false, NULL,                 NULL,                 'decision'),
  ('appendix',        'Appendix and Nominal Detail',       15, false, NULL,                 NULL,                 'appendix')
) AS s(section_key, title, position, mandatory, src, persp, ptype)
WHERE t.template_key = 'MANAGEMENT_ACCOUNTING_REPORT'
ON CONFLICT (template_id, section_key) DO NOTHING;

-- Finance Board Deck sections.
INSERT INTO finance.report_template_section (template_id, section_key, title, position, mandatory, default_source_key, default_ai_perspective, default_page_type)
SELECT t.template_id, s.section_key, s.title, s.position, s.mandatory, s.src, s.persp, s.ptype
FROM finance.report_template t
CROSS JOIN (VALUES
  ('cover',        'Cover Page',                       1,  true,  NULL,                 NULL,               'cover'),
  ('exec_summary', 'Finance Director Executive Summary',2, true,  'executive_hub',      'FINANCE_DIRECTOR', 'exec_summary'),
  ('decisions',    'Decisions Required',               3,  true,  NULL,                 NULL,               'decision'),
  ('health',       'Financial Health',                 4,  false, 'management_accounts','FINANCE_DIRECTOR', 'content'),
  ('revenue',      'Revenue and Growth',               5,  false, 'management_accounts','FPA',              'content'),
  ('ebitda',       'EBITDA and Profitability',         6,  false, 'management_accounts','FINANCE_DIRECTOR', 'content'),
  ('cash',         'Cash and Liquidity',               7,  false, 'cash',               'CASH_TREASURY',    'content'),
  ('forecast',     'Forecast and Outlook',             8,  false, 'forecast',           'FPA',              'content'),
  ('portfolio',    'Store Portfolio Performance',      9,  false, 'store_ranking',      'COMMERCIAL_FINANCE','content'),
  ('franchise',    'Franchise and Wholesale',          10, false, 'franchise',          NULL,               'content'),
  ('risks',        'Strategic Risks',                  11, false, 'executive_hub',      'RISK',             'risk_opp'),
  ('opportunities','Opportunities and Value Creation', 12, false, 'executive_hub',      'OPPORTUNITY',      'risk_opp'),
  ('actions',      'Key Actions and Ownership',        13, false, 'actions',            'ACTION',           'action'),
  ('appendix',     'Appendix',                         14, false, NULL,                 NULL,               'appendix')
) AS s(section_key, title, position, mandatory, src, persp, ptype)
WHERE t.template_key = 'FINANCE_BOARD_DECK'
ON CONFLICT (template_id, section_key) DO NOTHING;

-- Budget & Forecasts Deck sections.
INSERT INTO finance.report_template_section (template_id, section_key, title, position, mandatory, default_source_key, default_ai_perspective, default_page_type)
SELECT t.template_id, s.section_key, s.title, s.position, s.mandatory, s.src, s.persp, s.ptype
FROM finance.report_template t
CROSS JOIN (VALUES
  ('cover',        'Cover Page',                    1,  true,  NULL,        NULL,               'cover'),
  ('exec_summary', 'Executive Planning Summary',    2,  true,  'forecast',  'FPA',              'exec_summary'),
  ('assumptions',  'Planning Assumptions',          3,  false, 'forecast',  'FPA',              'content'),
  ('sales',        'Sales Budget and Forecast',     4,  false, 'forecast',  'COMMERCIAL_FINANCE','content'),
  ('store_fcst',   'Store Forecast',                5,  false, 'forecast',  NULL,               'content'),
  ('margin',       'Gross Margin',                  6,  false, 'forecast',  'COMMERCIAL_FINANCE','content'),
  ('costs',        'Fixed and Variable Costs',      7,  false, 'forecast',  'FINANCE_DIRECTOR', 'content'),
  ('consol_pnl',   'Consolidated P&L',              8,  false, 'forecast',  'FINANCE_DIRECTOR', 'content'),
  ('cashflow',     'Cash-Flow Forecast',            9,  false, 'cash',      'CASH_TREASURY',    'content'),
  ('scenarios',    'Scenario Analysis',             10, false, 'forecast',  'FPA',              'content'),
  ('sensitivities','Sensitivities',                 11, false, 'forecast',  'RISK',             'content'),
  ('risk_opp',     'Risks and Opportunities',       12, false, 'forecast',  'RISK',             'risk_opp'),
  ('decisions',    'Required Decisions',            13, false, NULL,        NULL,               'decision'),
  ('appendix',     'Appendix',                      14, false, NULL,        NULL,               'appendix')
) AS s(section_key, title, position, mandatory, src, persp, ptype)
WHERE t.template_key = 'BUDGET_FORECASTS_DECK'
ON CONFLICT (template_id, section_key) DO NOTHING;

-- Franchise Deck sections.
INSERT INTO finance.report_template_section (template_id, section_key, title, position, mandatory, default_source_key, default_ai_perspective, default_page_type)
SELECT t.template_id, s.section_key, s.title, s.position, s.mandatory, s.src, s.persp, s.ptype
FROM finance.report_template t
CROSS JOIN (VALUES
  ('cover',        'Cover Page',                     1,  true,  NULL,          NULL,               'cover'),
  ('exec_summary', 'Executive Franchise Summary',    2,  true,  'franchise',   'EXECUTIVE',        'exec_summary'),
  ('portfolio',    'Franchise Portfolio',            3,  false, 'franchise',   NULL,               'content'),
  ('sales',        'Franchise Sales',                4,  false, 'franchise',   'COMMERCIAL_FINANCE','content'),
  ('lfl',          'Like-for-Like Performance',      5,  false, 'franchise',   'COMMERCIAL_FINANCE','content'),
  ('wholesale',    'Wholesale Product Sales',        6,  false, 'franchise',   NULL,               'content'),
  ('royalties',    'Royalties and Fees',             7,  false, 'franchise',   NULL,               'content'),
  ('margin',       'Franchise Gross Margin',         8,  false, 'franchise',   'COMMERCIAL_FINANCE','content'),
  ('receivables',  'Franchise Receivables',          9,  false, 'franchise',   'CASH_TREASURY',    'content'),
  ('aged_debt',    'Aged Debt',                      10, false, 'franchise',   'RISK',             'content'),
  ('credit',       'Credit Limits and Exposure',     11, false, 'franchise',   'RISK',             'content'),
  ('pipeline',     'New Franchise Pipeline',         12, false, 'franchise',   NULL,               'content'),
  ('risk_opp',     'Risks and Opportunities',        13, false, 'franchise',   'RISK',             'risk_opp'),
  ('actions',      'Priority Actions',               14, false, 'actions',     'ACTION',           'action'),
  ('appendix',     'Appendix',                       15, false, NULL,          NULL,               'appendix')
) AS s(section_key, title, position, mandatory, src, persp, ptype)
WHERE t.template_key = 'FRANCHISE_DECK'
ON CONFLICT (template_id, section_key) DO NOTHING;

-- ---------------------------------------------------------------------------
-- Intelligence Layer: model + prompt for report commentary (reuses migration
-- 038 tables). Swappable without a deploy. The 10 perspectives select a lens;
-- the single prompt enforces governance (governed figures only, draft only).
-- ---------------------------------------------------------------------------
INSERT INTO intelligence.model_configuration (use_case, model, effort, max_tokens, timeout_ms, prompt_code, notes)
SELECT 'REPORT_COMMENTARY', 'claude-sonnet-5', 'high', 3500, 60000, 'REPORT_COMMENTARY_V1',
       'Drafts governed report commentary (Corporate Reporting Centre) for human sign-off.'
WHERE NOT EXISTS (SELECT 1 FROM intelligence.model_configuration WHERE use_case = 'REPORT_COMMENTARY');

INSERT INTO intelligence.prompt_version (prompt_code, version, system_prompt, output_schema, created_by) VALUES
  ('REPORT_COMMENTARY_V1', 1,
   'You are drafting a section of a corporate finance report for Miniso UK, for a human reviewer to check and sign off before use. You will be given a report context (template, period, data-through date, audience, section, comparison basis, commentary perspective and detail level) and a block of GOVERNED FACTS. Use ONLY those figures — never invent, estimate or introduce any number that is not present. Write in the requested perspective and tone, at the requested detail level. Explain what the figures show, what changed versus the stated comparison basis, the drivers evident in the data, and what to watch. Distinguish fact from interpretation. State the period and basis. Flag anything working/unapproved and any stale or missing data as a limitation. Use UK finance terminology and en-GB formatting (£ with comma thousands separators; negatives in brackets). This is a DRAFT for human sign-off, not a final or published statement; anything Board/investor-facing must be reviewed by a person before use. You do not take any action and cannot issue, send or approve anything.',
   '{"type":"object","additionalProperties":false,"required":["headline","body","confidence","sources"],"properties":{"headline":{"type":"string"},"body":{"type":"string"},"drivers":{"type":"array","items":{"type":"string"}},"risks":{"type":"array","items":{"type":"string"}},"opportunities":{"type":"array","items":{"type":"string"}},"recommended_actions":{"type":"array","items":{"type":"string"}},"financial_effect":{"type":"string"},"data_limitations":{"type":"array","items":{"type":"string"}},"confidence":{"type":"object","additionalProperties":false,"required":["level","reason"],"properties":{"level":{"type":"string","enum":["HIGH","MEDIUM","LOW"]},"reason":{"type":"string"}}},"sources":{"type":"array","items":{"type":"string"}}}}'::jsonb,
   'migration 045')
ON CONFLICT (prompt_code, version) DO NOTHING;

COMMIT;
