-- Migration 046 — Purchase Order Tracker (OPERATE)
-- Departments raise a P.O here after generating the P.O number in Xero. The P.O
-- carries its commercial header, a department tag, and an optional recharge
-- allocation across stores (percentages of the total value that must sum to
-- 100%). Marketing spend additionally records whether it is part of the
-- marketing levy: if it is, stores are allocated without invoicing; if not,
-- finance issues an invoice. A P.O moves to PENDING_SIGNOFF once complete; the
-- department-head sign-off itself is part of the forthcoming user-controls work.
--
-- Additive and idempotent. Safe to re-run.
--
-- ROLLBACK:
--   DROP TABLE IF EXISTS finance.purchase_order_recharge;
--   DROP TABLE IF EXISTS finance.purchase_order;

BEGIN;

CREATE TABLE IF NOT EXISTS finance.purchase_order (
  po_id            bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  po_date          date,
  supplier         varchar(200),
  payment_terms    varchar(80),
  payment_date     date,
  currency         varchar(8) DEFAULT 'GBP',
  payment_value    numeric(18,2),            -- total P.O value
  vat_amount       numeric(18,2),
  po_category      varchar(80),
  xero_po_number   varchar(60),              -- generated in Xero first, entered here
  fulfilment_date  date,
  fulfilment_period varchar(20),             -- e.g. 'YYYY-MM' or a free label
  department       varchar(120),             -- departmental spend tag
  is_marketing     boolean NOT NULL DEFAULT false,
  marketing_levy   boolean,                  -- only meaningful when is_marketing; null = unanswered
  recharge_enabled boolean NOT NULL DEFAULT false,
  invoice_action   varchar(24),              -- LEVY_NO_INVOICE | FINANCE_TO_INVOICE | STANDARD | NONE
  status           varchar(20) NOT NULL DEFAULT 'DRAFT'
                   CHECK (status IN ('DRAFT','PENDING_SIGNOFF','APPROVED','REJECTED','CANCELLED')),
  notes            text,
  created_by       varchar(160),
  signed_off_by    varchar(160),             -- set by the department-head sign-off (user-controls, later)
  signed_off_at    timestamptz,
  created_at       timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at       timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS ix_purchase_order_recent ON finance.purchase_order (created_at DESC);
CREATE INDEX IF NOT EXISTS ix_purchase_order_status ON finance.purchase_order (status);
CREATE INDEX IF NOT EXISTS ix_purchase_order_dept   ON finance.purchase_order (department);
CREATE INDEX IF NOT EXISTS ix_purchase_order_owner  ON finance.purchase_order (created_by);

-- Recharge allocation: a P.O value split across selected stores by percentage.
-- The percentages must total 100% before a P.O can go to sign-off (enforced in
-- the rules layer). amount is the derived £ share, stored for convenience.
CREATE TABLE IF NOT EXISTS finance.purchase_order_recharge (
  recharge_id  bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  po_id        bigint NOT NULL REFERENCES finance.purchase_order(po_id) ON DELETE CASCADE,
  store_code   varchar(40),
  store_name   varchar(160),
  pct          numeric(7,4) NOT NULL DEFAULT 0,   -- percentage of total P.O value
  amount       numeric(18,2) NOT NULL DEFAULT 0,  -- derived: pct/100 * payment_value
  created_at   timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS ix_po_recharge_po ON finance.purchase_order_recharge (po_id);

COMMIT;
