-- Migration 048 — Department sign-off + per-department page access
-- Two governance tables behind the Users, Roles & Permissions screen:
--   1. department_signoff — who signs off a department's budgets and P.Os. A
--      department can have MORE THAN ONE approver (e.g. Finance = Kris + Sergio).
--   2. nav_visibility — which navigation headers / sub-headers a department may
--      see. A row means that node is HIDDEN for that department; no row = visible
--      (default open). Admins always see everything.
--
-- Additive and idempotent. Safe to re-run.
--
-- ROLLBACK:
--   DROP TABLE IF EXISTS governance.department_signoff;
--   DROP TABLE IF EXISTS governance.nav_visibility;

BEGIN;

CREATE TABLE IF NOT EXISTS governance.department_signoff (
  signoff_id    bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  department    varchar(120) NOT NULL,
  signoff_email varchar(200) NOT NULL,
  signoff_name  varchar(160),
  created_by    varchar(160),
  created_at    timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UNIQUE (department, signoff_email)
);
CREATE INDEX IF NOT EXISTS ix_dept_signoff_dept ON governance.department_signoff (department);

-- Hidden navigation nodes per department. node_key is 'sec:<sectionKey>' for a
-- header or 'item:<sectionKey>:<itemId>' for a sub-header (see
-- lib/nav-visibility-rules.js). Presence = hidden for that department.
CREATE TABLE IF NOT EXISTS governance.nav_visibility (
  department  varchar(120) NOT NULL,
  node_key    varchar(200) NOT NULL,
  created_by  varchar(160),
  created_at  timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (department, node_key)
);
CREATE INDEX IF NOT EXISTS ix_nav_visibility_dept ON governance.nav_visibility (department);

COMMIT;
