-- Migration 049 — Departmental Budgets (Plan – HO)
-- A department head builds a budget for their department: cost lines grouped into
-- categories, phased across the 12 months of the budget year (Jan–Dec), with a
-- prior-year comparator. Versions are kept (never overwritten) and move
-- DRAFT → SUBMITTED → APPROVED, signed off by the department's approvers set in
-- GOVERN → Users, Roles & Permissions (migration 048).
--
--   1. dept_budget          — the budget header (department × year × version).
--   2. dept_budget_line     — one row per cost line: category, label, prior year
--                             and the 12 monthly figures (m01=Jan … m12=Dec).
--   3. dept_budget_template — seeded starter cost lines per department, copied
--                             into a new budget so heads start from a sensible set.
--
-- Additive and idempotent. Safe to re-run.
--
-- ROLLBACK:
--   DROP TABLE IF EXISTS finance.dept_budget_line;
--   DROP TABLE IF EXISTS finance.dept_budget;
--   DROP TABLE IF EXISTS finance.dept_budget_template;

BEGIN;

CREATE TABLE IF NOT EXISTS finance.dept_budget (
  budget_id     bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  department    varchar(120) NOT NULL,
  budget_year   int NOT NULL,
  version_label varchar(80) NOT NULL DEFAULT 'Working draft',
  status        varchar(20) NOT NULL DEFAULT 'DRAFT',   -- DRAFT / SUBMITTED / APPROVED
  notes         text,
  created_by    varchar(160),
  created_at    timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at    timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
  submitted_by  varchar(160),
  submitted_at  timestamptz,
  approved_by   varchar(160),
  approved_at   timestamptz,
  UNIQUE (department, budget_year, version_label)
);
CREATE INDEX IF NOT EXISTS ix_dept_budget_dept_year ON finance.dept_budget (department, budget_year);

CREATE TABLE IF NOT EXISTS finance.dept_budget_line (
  line_id     bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  budget_id   bigint NOT NULL REFERENCES finance.dept_budget (budget_id) ON DELETE CASCADE,
  category    varchar(120) NOT NULL DEFAULT 'General',
  line_label  varchar(160) NOT NULL,
  sort_order  int NOT NULL DEFAULT 0,
  prior_year  numeric(14,2) NOT NULL DEFAULT 0,
  m01 numeric(14,2) NOT NULL DEFAULT 0, m02 numeric(14,2) NOT NULL DEFAULT 0,
  m03 numeric(14,2) NOT NULL DEFAULT 0, m04 numeric(14,2) NOT NULL DEFAULT 0,
  m05 numeric(14,2) NOT NULL DEFAULT 0, m06 numeric(14,2) NOT NULL DEFAULT 0,
  m07 numeric(14,2) NOT NULL DEFAULT 0, m08 numeric(14,2) NOT NULL DEFAULT 0,
  m09 numeric(14,2) NOT NULL DEFAULT 0, m10 numeric(14,2) NOT NULL DEFAULT 0,
  m11 numeric(14,2) NOT NULL DEFAULT 0, m12 numeric(14,2) NOT NULL DEFAULT 0
);
CREATE INDEX IF NOT EXISTS ix_dept_budget_line_budget ON finance.dept_budget_line (budget_id);

CREATE TABLE IF NOT EXISTS finance.dept_budget_template (
  template_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  department  varchar(120) NOT NULL,
  category    varchar(120) NOT NULL,
  line_label  varchar(160) NOT NULL,
  sort_order  int NOT NULL DEFAULT 0,
  UNIQUE (department, category, line_label)
);

-- Starter cost lines per department (editable once copied into a budget).
INSERT INTO finance.dept_budget_template (department, category, line_label, sort_order) VALUES
  -- Marketing (the worked example)
  ('Marketing','Media','Paid media — digital',10),
  ('Marketing','Media','Paid media — offline & print',20),
  ('Marketing','Media','Agency fees',30),
  ('Marketing','Brand & Content','Photography & content production',40),
  ('Marketing','Brand & Content','Influencers & partnerships',50),
  ('Marketing','Brand & Content','PR',60),
  ('Marketing','Events & Activations','Store openings & events',70),
  ('Marketing','Events & Activations','Sponsorships',80),
  ('Marketing','Store Marketing','In-store POS & signage',90),
  ('Marketing','Store Marketing','Local store marketing',100),
  ('Marketing','Digital & CRM','Website & app',110),
  ('Marketing','Digital & CRM','Email, CRM & loyalty',120),
  ('Marketing','Digital & CRM','Social & marketing tools',130),
  ('Marketing','Other','Market research',140),
  ('Marketing','Other','Contingency',150),
  -- Finance
  ('Finance','People','Salaries & wages',10),
  ('Finance','People','Training & development',20),
  ('Finance','Professional Fees','Audit & accountancy',30),
  ('Finance','Professional Fees','Tax advisory',40),
  ('Finance','Professional Fees','Legal',50),
  ('Finance','Systems','Finance software & subscriptions',60),
  ('Finance','Systems','Banking charges',70),
  ('Finance','Other','Travel & expenses',80),
  ('Finance','Other','Contingency',90),
  -- Merchandising
  ('Merchandising','People','Salaries & wages',10),
  ('Merchandising','Buying','Samples & product costs',20),
  ('Merchandising','Buying','Trade shows & sourcing travel',30),
  ('Merchandising','Systems','Merchandising software',40),
  ('Merchandising','Other','Contingency',50),
  -- Operations
  ('Operations','People','Area management',10),
  ('Operations','People','Store labour support',20),
  ('Operations','Store Running Costs','Consumables & supplies',30),
  ('Operations','Store Running Costs','Equipment & maintenance',40),
  ('Operations','Systems','Ops software & POS support',50),
  ('Operations','Other','Travel',60),
  ('Operations','Other','Contingency',70),
  -- HR
  ('HR','People','Salaries & wages',10),
  ('HR','Recruitment','Agency & advertising',20),
  ('HR','Recruitment','Onboarding',30),
  ('HR','Development','Training & L&D',40),
  ('HR','Development','Engagement & wellbeing',50),
  ('HR','Systems','HR & payroll software',60),
  ('HR','Other','Contingency',70),
  -- Logistics
  ('Logistics','People','Warehouse labour',10),
  ('Logistics','Distribution','Freight & carriage',20),
  ('Logistics','Distribution','Duty & clearance',30),
  ('Logistics','Distribution','Warehousing & storage',40),
  ('Logistics','Systems','WMS & tracking software',50),
  ('Logistics','Other','Packaging',60),
  ('Logistics','Other','Contingency',70),
  -- Architecture & Build
  ('Architecture & Build','People','Project management',10),
  ('Architecture & Build','Store Build','Fit-out & construction',20),
  ('Architecture & Build','Store Build','Fixtures & fittings',30),
  ('Architecture & Build','Store Build','Signage & branding',40),
  ('Architecture & Build','Professional Fees','Architects & surveyors',50),
  ('Architecture & Build','Professional Fees','Landlord & legal',60),
  ('Architecture & Build','Other','Contingency',70)
ON CONFLICT (department, category, line_label) DO NOTHING;

COMMIT;
