-- Migration 050 — Departmental Budgets, planning upgrade (Phase 1)
-- Turns the budget grid into a budget control centre:
--   · dept_budget.target_amount — the Finance-set top-down spending envelope.
--   · a 5-stage approval workflow (DRAFT → FINANCE_REVIEW → DEPT_APPROVAL →
--     SLT_APPROVAL → LOCKED), with legacy statuses mapped forward.
--   · dept_budget_line.commentary — per-line justification / change explanation.
--   · dept_budget_event — the approval timeline (one row per transition/comment).
--
-- Additive and idempotent. Safe to re-run.
--
-- ROLLBACK:
--   DROP TABLE IF EXISTS finance.dept_budget_event;
--   ALTER TABLE finance.dept_budget_line DROP COLUMN IF EXISTS commentary;
--   ALTER TABLE finance.dept_budget DROP COLUMN IF EXISTS target_amount;
--   -- (status values are left as-is on rollback)

BEGIN;

ALTER TABLE finance.dept_budget ADD COLUMN IF NOT EXISTS target_amount numeric(14,2);
ALTER TABLE finance.dept_budget_line ADD COLUMN IF NOT EXISTS commentary text;

-- Map the old three-state workflow onto the new chain (no-op once migrated;
-- the module is new so there is little or no live data to move).
UPDATE finance.dept_budget SET status = 'FINANCE_REVIEW' WHERE status = 'SUBMITTED';
UPDATE finance.dept_budget SET status = 'LOCKED'         WHERE status = 'APPROVED';

-- The approval timeline: every stage transition (and any returned-with-note) is
-- recorded here so the budget carries its own audit-friendly history.
CREATE TABLE IF NOT EXISTS finance.dept_budget_event (
  event_id    bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  budget_id   bigint NOT NULL REFERENCES finance.dept_budget (budget_id) ON DELETE CASCADE,
  event_type  varchar(40) NOT NULL,        -- transition action, or 'comment'
  from_status varchar(20),
  to_status   varchar(20),
  actor       varchar(160),
  note        text,
  created_at  timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS ix_dept_budget_event_budget ON finance.dept_budget_event (budget_id, created_at);

COMMIT;
