-- Migration 051 — Departmental Budgets, operational planning (Phase 2)
-- Lets a department build its budget in its own language — campaigns, projects,
-- contracts — which then generate the financial cost lines and monthly phasing.
--
--   · dept_budget_initiative      — an operational unit (campaign / project /
--     contract / programme) with its objective, owner, active month range, scope,
--     expenditure classification and expected commercial outcome.
--   · dept_budget_initiative_cost — the spend that makes up an initiative, each
--     with its own phasing method; these aggregate into the financial grid.
--   · dept_budget_line gains `source` (MANUAL vs INITIATIVE-generated) and
--     `classification`, so generated lines and hand-entered lines coexist safely.
--
-- Additive and idempotent. Safe to re-run.
--
-- ROLLBACK:
--   DROP TABLE IF EXISTS finance.dept_budget_initiative_cost;
--   DROP TABLE IF EXISTS finance.dept_budget_initiative;
--   ALTER TABLE finance.dept_budget_line DROP COLUMN IF EXISTS source;
--   ALTER TABLE finance.dept_budget_line DROP COLUMN IF EXISTS classification;

BEGIN;

ALTER TABLE finance.dept_budget_line ADD COLUMN IF NOT EXISTS source varchar(20) NOT NULL DEFAULT 'MANUAL';
ALTER TABLE finance.dept_budget_line ADD COLUMN IF NOT EXISTS classification varchar(20);

CREATE TABLE IF NOT EXISTS finance.dept_budget_initiative (
  initiative_id      bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  budget_id          bigint NOT NULL REFERENCES finance.dept_budget (budget_id) ON DELETE CASCADE,
  name               varchar(200) NOT NULL,
  kind               varchar(30) NOT NULL DEFAULT 'INITIATIVE',   -- CAMPAIGN / PROJECT / CONTRACT / PROGRAMME / INITIATIVE
  objective          text,
  owner              varchar(160),
  scope              varchar(200),                                -- e.g. "All stores", "HO", a region
  classification     varchar(20) NOT NULL DEFAULT 'BAU',          -- COMMITTED / BAU / GROWTH / STRATEGIC / DISCRETIONARY / CONTINGENCY
  start_month        int NOT NULL DEFAULT 1,                      -- 1–12 (Jan–Dec)
  end_month          int NOT NULL DEFAULT 12,
  incremental_sales  numeric(14,2) NOT NULL DEFAULT 0,
  incremental_margin numeric(14,2) NOT NULL DEFAULT 0,
  notes              text,
  sort_order         int NOT NULL DEFAULT 0,
  created_by         varchar(160),
  created_at         timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at         timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS ix_dept_budget_initiative_budget ON finance.dept_budget_initiative (budget_id);

CREATE TABLE IF NOT EXISTS finance.dept_budget_initiative_cost (
  cost_id       bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  initiative_id bigint NOT NULL REFERENCES finance.dept_budget_initiative (initiative_id) ON DELETE CASCADE,
  category      varchar(120) NOT NULL DEFAULT 'General',
  line_label    varchar(160) NOT NULL,
  amount        numeric(14,2) NOT NULL DEFAULT 0,
  phasing       varchar(20) NOT NULL DEFAULT 'EVEN',              -- EVEN / ONEOFF / QUARTERLY / MANUAL
  one_off_month int,                                             -- 1–12 when phasing = ONEOFF
  m01 numeric(14,2) NOT NULL DEFAULT 0, m02 numeric(14,2) NOT NULL DEFAULT 0,
  m03 numeric(14,2) NOT NULL DEFAULT 0, m04 numeric(14,2) NOT NULL DEFAULT 0,
  m05 numeric(14,2) NOT NULL DEFAULT 0, m06 numeric(14,2) NOT NULL DEFAULT 0,
  m07 numeric(14,2) NOT NULL DEFAULT 0, m08 numeric(14,2) NOT NULL DEFAULT 0,
  m09 numeric(14,2) NOT NULL DEFAULT 0, m10 numeric(14,2) NOT NULL DEFAULT 0,
  m11 numeric(14,2) NOT NULL DEFAULT 0, m12 numeric(14,2) NOT NULL DEFAULT 0,
  sort_order    int NOT NULL DEFAULT 0
);
CREATE INDEX IF NOT EXISTS ix_dept_budget_initiative_cost_init ON finance.dept_budget_initiative_cost (initiative_id);

COMMIT;
