-- Migration 055 — Driver-based planning engine: foundation (Phase 1)
-- The first slice of the driver-based budget/forecast/consolidated-P&L engine.
-- It is ADDITIVE and self-contained: a new `planning` schema that coexists with
-- the existing forecast/budget tables and does NOT touch pl_format, forecast_line
-- or any live screen. It lays down the two governed registers the rest of the
-- engine builds on:
--   · planning.driver_definition  — the Driver Library (what a driver is)
--   · planning.driver_assumption  — the Assumption Register (a driver's value at
--                                    a resolution level: company/region/entity/store)
--   · planning.scenario           — the scenario dimension (base/upside/…)
-- Plan versions, plan lines, sales/payroll/cost drivers, results and consolidation
-- arrive in later phases (migrations 056+).
--
-- Idempotent. Safe to re-run.
--
-- ROLLBACK:
--   DROP SCHEMA IF EXISTS planning CASCADE;

BEGIN;

CREATE SCHEMA IF NOT EXISTS planning;

-- ---- Scenario dimension -------------------------------------------------
-- The driver architecture is scenario-aware from the start; the same drivers
-- carry different assumption values per scenario (base / upside / downside / …).
CREATE TABLE IF NOT EXISTS planning.scenario (
  scenario_code varchar(30) PRIMARY KEY,          -- BASE / UPSIDE / DOWNSIDE / STRETCH
  name          varchar(80)  NOT NULL,
  description   text,
  is_default    boolean NOT NULL DEFAULT false,
  is_active     boolean NOT NULL DEFAULT true,
  sort_order    integer NOT NULL DEFAULT 0
);

-- ---- Driver Library -----------------------------------------------------
-- The governed catalogue of drivers. A driver DEFINES a calculation shape; the
-- numbers live in the Assumption Register. permitted_scopes / permitted_nominals
-- constrain where a driver may be used.
CREATE TABLE IF NOT EXISTS planning.driver_definition (
  driver_code        varchar(50) PRIMARY KEY,      -- e.g. FOOTFALL, CONVERSION, ATV, PCT_OF_SALES, HOLIDAY_PAY_RATE
  description        varchar(200) NOT NULL,
  category           varchar(20) NOT NULL,         -- SALES / COST / PAYROLL / FRANCHISE
  unit               varchar(30),                  -- COUNT / PERCENT / GBP / RATIO / DAYS
  calc_rule          varchar(50),                  -- FOOTFALL_X_CONVERSION_X_ATV / PCT_OF_SALES / PCT_OF_BASIC_PAY / PCT_OF_PENSIONABLE / FIXED_MONTHLY / DIRECT_INPUT / …
  permitted_scopes   text[] NOT NULL DEFAULT '{}', -- COMPANY_STORE / HEAD_OFFICE / FRANCHISE_STORE
  permitted_nominals text[],                        -- NULL = any nominal
  effective_start    date,
  effective_end      date,
  is_active          boolean NOT NULL DEFAULT true,
  owner              varchar(120),
  approval_status    varchar(12) NOT NULL DEFAULT 'DRAFT',   -- DRAFT / APPROVED / RETIRED
  version            integer NOT NULL DEFAULT 1,
  created_by         varchar(120),
  created_at         timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at         timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- ---- Assumption Register ------------------------------------------------
-- A driver's value at a resolution level. Levels nest COMPANY → REGION → ENTITY
-- → STORE; the most specific APPROVED assumption wins at read time (resolved in
-- lib/planning-rules.js). period NULL = applies to every period (a constant);
-- a period-specific row overrides the constant for that month.
CREATE TABLE IF NOT EXISTS planning.driver_assumption (
  assumption_id   bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  driver_code     varchar(50) NOT NULL REFERENCES planning.driver_definition(driver_code),
  scope           varchar(24) NOT NULL,            -- COMPANY_STORE / HEAD_OFFICE / FRANCHISE_STORE
  level           varchar(12) NOT NULL,            -- COMPANY / REGION / ENTITY / STORE
  level_key       varchar(120),                    -- region name, entity code, or store_code; NULL for COMPANY
  fiscal_year     char(4),
  scenario_code   varchar(30) NOT NULL DEFAULT 'BASE' REFERENCES planning.scenario(scenario_code),
  version_label   varchar(120),                    -- forward-compat with plan versions; NULL = working assumption
  period          char(7),                         -- 'YYYY-MM'; NULL = all periods
  value           numeric(20,6) NOT NULL,
  unit            varchar(30),
  source          varchar(120),
  owner           varchar(120),
  commentary      text,
  approval_status varchar(12) NOT NULL DEFAULT 'DRAFT',   -- DRAFT / APPROVED
  effective_start date,
  effective_end   date,
  created_by      varchar(120),
  reviewed_by     varchar(120),
  created_at      timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at      timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS ix_driver_assumption_lookup ON planning.driver_assumption (driver_code, scope, scenario_code, fiscal_year);
CREATE INDEX IF NOT EXISTS ix_driver_assumption_level  ON planning.driver_assumption (level, level_key);

-- ---- Seed: scenarios ----------------------------------------------------
INSERT INTO planning.scenario (scenario_code, name, description, is_default, sort_order) VALUES
  ('BASE',     'Base case',     'The central planning case.',                 true,  1),
  ('UPSIDE',   'Upside case',   'Favourable trading and cost assumptions.',   false, 2),
  ('DOWNSIDE', 'Downside case', 'Adverse trading and cost assumptions.',      false, 3),
  ('STRETCH',  'Stretch case',  'Ambitious target case.',                     false, 4)
ON CONFLICT (scenario_code) DO NOTHING;

-- ---- Seed: starter Driver Library --------------------------------------
-- The initial governed drivers (Driver Library §17). Seeded APPROVED so the
-- engine has a working catalogue; values are supplied via the Assumption
-- Register per store/period/scenario.
INSERT INTO planning.driver_definition (driver_code, description, category, unit, calc_rule, permitted_scopes, approval_status, owner, created_by) VALUES
  -- Sales drivers
  ('FOOTFALL',        'Store footfall (visitors)',              'SALES',  'COUNT',   'DIRECT_INPUT',                 '{COMPANY_STORE,FRANCHISE_STORE}', 'APPROVED', 'Finance', 'migration'),
  ('CONVERSION',      'Conversion rate (transactions/footfall)','SALES',  'PERCENT', 'DIRECT_INPUT',                 '{COMPANY_STORE,FRANCHISE_STORE}', 'APPROVED', 'Finance', 'migration'),
  ('ATV',             'Average transaction value',              'SALES',  'GBP',     'DIRECT_INPUT',                 '{COMPANY_STORE,FRANCHISE_STORE}', 'APPROVED', 'Finance', 'migration'),
  ('TRADING_DAYS',    'Available trading days',                 'SALES',  'DAYS',    'DIRECT_INPUT',                 '{COMPANY_STORE,FRANCHISE_STORE}', 'APPROVED', 'Finance', 'migration'),
  ('LFL_GROWTH',      'Like-for-like growth',                   'SALES',  'PERCENT', 'DIRECT_INPUT',                 '{COMPANY_STORE,FRANCHISE_STORE}', 'APPROVED', 'Finance', 'migration'),
  ('SEASONAL_INDEX',  'Seasonal index',                         'SALES',  'RATIO',   'DIRECT_INPUT',                 '{COMPANY_STORE,FRANCHISE_STORE}', 'APPROVED', 'Finance', 'migration'),
  -- Cost drivers
  ('PCT_OF_SALES',    'Cost as a percentage of net sales',      'COST',   'PERCENT', 'PCT_OF_SALES',                 '{COMPANY_STORE,HEAD_OFFICE,FRANCHISE_STORE}', 'APPROVED', 'Finance', 'migration'),
  ('FIXED_MONTHLY',   'Fixed monthly amount',                   'COST',   'GBP',     'FIXED_MONTHLY',                '{COMPANY_STORE,HEAD_OFFICE,FRANCHISE_STORE}', 'APPROVED', 'Finance', 'migration'),
  ('ANNUAL_INFLATION','Annual inflation on a fixed cost',       'COST',   'PERCENT', 'ANNUAL_INFLATION',             '{COMPANY_STORE,HEAD_OFFICE,FRANCHISE_STORE}', 'APPROVED', 'Finance', 'migration'),
  -- Payroll drivers
  ('HOLIDAY_PAY_RATE','Holiday pay as % of basic pay',          'PAYROLL','PERCENT', 'PCT_OF_BASIC_PAY',             '{COMPANY_STORE,HEAD_OFFICE,FRANCHISE_STORE}', 'APPROVED', 'Finance', 'migration'),
  ('PENSION_RATE',    'Employer pension as % of pensionable pay','PAYROLL','PERCENT','PCT_OF_PENSIONABLE',           '{COMPANY_STORE,HEAD_OFFICE,FRANCHISE_STORE}', 'APPROVED', 'Finance', 'migration'),
  ('EMPLOYER_NI_RATE','Employer NI as % of NI pay base',        'PAYROLL','PERCENT', 'PCT_OF_PENSIONABLE',           '{COMPANY_STORE,HEAD_OFFICE,FRANCHISE_STORE}', 'APPROVED', 'Finance', 'migration'),
  -- Franchise drivers
  ('ROYALTY_RATE',    'Royalty income as % of franchise retail sales', 'FRANCHISE', 'PERCENT', 'PCT_OF_SALES',       '{FRANCHISE_STORE}', 'APPROVED', 'Finance', 'migration'),
  ('MARKETING_CONTRIB_RATE','Marketing contribution as % of franchise retail sales','FRANCHISE','PERCENT','PCT_OF_SALES','{FRANCHISE_STORE}', 'APPROVED', 'Finance', 'migration'),
  ('WHOLESALE_PURCHASE_RATIO','Wholesale product sales as % of franchise retail sales','FRANCHISE','PERCENT','PCT_OF_SALES','{FRANCHISE_STORE}', 'APPROVED', 'Finance', 'migration'),
  ('BAD_DEBT_RATE',   'Bad-debt provision as % of franchise income',   'FRANCHISE', 'PERCENT', 'PCT_OF_SALES',       '{FRANCHISE_STORE}', 'APPROVED', 'Finance', 'migration')
ON CONFLICT (driver_code) DO NOTHING;

-- ---- Seed: company-default payroll on-cost rates ------------------------
-- Governed defaults (previously hard-coded in lib/forecast-rules.js): holiday
-- 12.07% of basic; pension 3% of pensionable; employer NI 0% for now (a
-- configurable effective rate — thresholds arrive later without an engine
-- rebuild). COMPANY level, BASE scenario, all periods.
INSERT INTO planning.driver_assumption (driver_code, scope, level, level_key, scenario_code, value, unit, source, owner, approval_status, created_by)
SELECT v.driver_code, s.scope, 'COMPANY', NULL, 'BASE', v.value, 'PERCENT', 'Migration default', 'Finance', 'APPROVED', 'migration'
FROM (VALUES
  ('HOLIDAY_PAY_RATE', 0.120700),
  ('PENSION_RATE',     0.030000),
  ('EMPLOYER_NI_RATE', 0.000000)
) AS v(driver_code, value)
CROSS JOIN (VALUES ('COMPANY_STORE'), ('HEAD_OFFICE'), ('FRANCHISE_STORE')) AS s(scope)
WHERE NOT EXISTS (
  SELECT 1 FROM planning.driver_assumption a
   WHERE a.driver_code = v.driver_code AND a.scope = s.scope AND a.level = 'COMPANY'
     AND a.level_key IS NULL AND a.scenario_code = 'BASE' AND a.period IS NULL
);

COMMIT;
