-- Migration 056 — Planning engine Phase 2a: plan versions, sales driver inputs,
-- and the calculated result grain (plan_line).
-- Builds on migration 055 (Driver Library + Assumption Register). Still additive
-- and isolated in the `planning` schema — no live screen, pl_format or
-- forecast_line is touched.
--
--   · planning.plan_version       — a named budget/forecast version (lifecycle)
--   · planning.sales_driver_input — store × period × version × scenario driver
--                                    inputs (footfall / conversion / ATV / method
--                                    / management adjustment / trading days)
--   · planning.plan_line          — THE calculated result grain. Every phase's
--                                    engine writes here, keyed by the account
--                                    NAME that the pl_format templates consume
--                                    (e.g. 'ST: Sales'), so scope/consolidated
--                                    P&Ls render through the existing templates
--                                    with no template change. Carries `lineage`
--                                    (the inputs/rate/base that produced it).
--
-- Idempotent. Safe to re-run.
--
-- ROLLBACK:
--   DROP TABLE IF EXISTS planning.plan_line;
--   DROP TABLE IF EXISTS planning.sales_driver_input;
--   DROP TABLE IF EXISTS planning.plan_version;

BEGIN;

-- ---- Plan versions ------------------------------------------------------
CREATE TABLE IF NOT EXISTS planning.plan_version (
  version_id    bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  label         varchar(120) NOT NULL,
  kind          varchar(10) NOT NULL DEFAULT 'FORECAST',   -- BUDGET / FORECAST
  fiscal_year   char(4),
  base_scenario varchar(30) NOT NULL DEFAULT 'BASE' REFERENCES planning.scenario(scenario_code),
  status        varchar(12) NOT NULL DEFAULT 'DRAFT',      -- DRAFT / APPROVED / LOCKED / ARCHIVED
  notes         text,
  created_by    varchar(120),
  created_at    timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
  approved_by   varchar(120),
  approved_at   timestamptz,
  updated_at    timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- ---- Sales driver inputs -----------------------------------------------
-- The store's monthly sales-driver forecast. Missing drivers fall back to the
-- Assumption Register at read/compute time (company→region→entity→store).
CREATE TABLE IF NOT EXISTS planning.sales_driver_input (
  input_id      bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  version_id    bigint NOT NULL REFERENCES planning.plan_version(version_id) ON DELETE CASCADE,
  scenario_code varchar(30) NOT NULL DEFAULT 'BASE' REFERENCES planning.scenario(scenario_code),
  scope         varchar(24) NOT NULL,             -- COMPANY_STORE / FRANCHISE_STORE
  store_code    varchar(40) NOT NULL,
  period        char(7) NOT NULL,                 -- YYYY-MM
  method        varchar(8) NOT NULL DEFAULT 'CORE',  -- CORE / DIRECT / HYBRID
  footfall      numeric(18,2),
  conversion    numeric(9,6),                     -- fraction 0..1
  atv           numeric(12,4),
  direct_sales  numeric(18,2),
  adjustment_amount numeric(18,2),
  adjustment_pct    numeric(9,6),
  trading_days  numeric(6,2),
  commentary    text,
  updated_by    varchar(120),
  updated_at    timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UNIQUE (version_id, scenario_code, store_code, period)
);
CREATE INDEX IF NOT EXISTS ix_sales_driver_input_ver ON planning.sales_driver_input (version_id, scenario_code, store_code);

-- ---- Plan lines (the calculated result grain) ---------------------------
-- One row per computed nominal × period. `nominal` is the account NAME that the
-- pl_format template maps (e.g. 'ST: Sales'). `source` tags which engine produced
-- it (SALES_DRIVER now; FIXED / PCT_OF_SALES / PAYROLL / MANUAL in later phases).
CREATE TABLE IF NOT EXISTS planning.plan_line (
  line_id       bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  version_id    bigint NOT NULL REFERENCES planning.plan_version(version_id) ON DELETE CASCADE,
  scenario_code varchar(30) NOT NULL DEFAULT 'BASE' REFERENCES planning.scenario(scenario_code),
  scope         varchar(24) NOT NULL,             -- COMPANY_STORE / HEAD_OFFICE / FRANCHISE_STORE / CONSOLIDATION_ADJUSTMENT
  store_code    varchar(40),                      -- NULL for HEAD_OFFICE
  entity_id     bigint,                           -- derived from the store (Store Master); nullable
  department    varchar(120),                     -- HEAD_OFFICE only
  nominal       varchar(180) NOT NULL,            -- account NAME matching pl_format line.accounts, e.g. 'ST: Sales'
  period        char(7) NOT NULL,                 -- YYYY-MM
  amount        numeric(20,6) NOT NULL DEFAULT 0,
  driver_code   varchar(50),
  source        varchar(20) NOT NULL DEFAULT 'ENGINE',  -- SALES_DRIVER / FIXED / PCT_OF_SALES / PAYROLL / MANUAL
  lineage       jsonb,                            -- inputs / rate / base that produced this amount
  calc_at       timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP
);
-- One computed value per (version, scenario, scope, store, nominal, period, source).
CREATE UNIQUE INDEX IF NOT EXISTS ux_plan_line_grain
  ON planning.plan_line (version_id, scenario_code, scope, COALESCE(store_code, ''), nominal, period, source);
CREATE INDEX IF NOT EXISTS ix_plan_line_read ON planning.plan_line (version_id, scenario_code, scope, period);

COMMIT;
