-- Migration 057 — Planning engine Phase 2b: cost behaviours (fixed + % of sales)
-- Builds on migrations 055 (drivers/assumptions) and 056 (plan_version, plan_line).
-- Additive and isolated in the `planning` schema — no live screen is touched.
--
--   · planning.cost_rule     — a cost line's behaviour for a version/scenario:
--        FIXED_MONTHLY  — a recurring monthly amount over [start_period,end_period],
--                         optionally with an annual increase; per-month values can
--                         be overridden (Method 1 = every month overridden).
--        PCT_OF_SALES   — rate × a sales base (a computed nominal, default 'ST: Sales').
--   · planning.cost_override — replaces a FIXED_MONTHLY rule's amount for ONE month
--                              (an explicit override is never silently changed when
--                              the recurring rule changes).
-- Computed values land in planning.plan_line (source FIXED / PCT_OF_SALES).
--
-- Idempotent. Safe to re-run.
--
-- ROLLBACK:
--   DROP TABLE IF EXISTS planning.cost_override;
--   DROP TABLE IF EXISTS planning.cost_rule;

BEGIN;

CREATE TABLE IF NOT EXISTS planning.cost_rule (
  rule_id        bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  version_id     bigint NOT NULL REFERENCES planning.plan_version(version_id) ON DELETE CASCADE,
  scenario_code  varchar(30) NOT NULL DEFAULT 'BASE' REFERENCES planning.scenario(scenario_code),
  scope          varchar(24) NOT NULL,             -- COMPANY_STORE / HEAD_OFFICE / FRANCHISE_STORE
  store_code     varchar(40),                      -- NULL for HEAD_OFFICE
  department     varchar(120),                     -- HEAD_OFFICE only
  nominal        varchar(180) NOT NULL,            -- the cost account NAME, e.g. 'ST: Rent'
  behaviour      varchar(20) NOT NULL,             -- FIXED_MONTHLY / PCT_OF_SALES
  monthly_amount numeric(20,6),                    -- FIXED_MONTHLY base
  annual_increase_pct numeric(9,6) NOT NULL DEFAULT 0,  -- FIXED_MONTHLY optional escalation
  rate           numeric(12,8),                    -- PCT_OF_SALES rate (fraction 0..1)
  sales_base     varchar(180) NOT NULL DEFAULT 'ST: Sales',  -- PCT_OF_SALES base nominal
  start_period   char(7),                          -- YYYY-MM (FIXED_MONTHLY)
  end_period     char(7),                          -- YYYY-MM (FIXED_MONTHLY)
  commentary     text,
  created_by     varchar(120),
  created_at     timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at     timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS ix_cost_rule_ver ON planning.cost_rule (version_id, scenario_code, scope, store_code);

CREATE TABLE IF NOT EXISTS planning.cost_override (
  override_id  bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  rule_id      bigint NOT NULL REFERENCES planning.cost_rule(rule_id) ON DELETE CASCADE,
  period       char(7) NOT NULL,                   -- YYYY-MM
  amount       numeric(20,6) NOT NULL,
  reason       text,
  created_by   varchar(120),
  created_at   timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UNIQUE (rule_id, period)
);

COMMIT;
