-- Migration 058 — Planning engine Phase 2c: the payroll chain
-- Builds on 055 (drivers/assumptions), 056 (plan_line) and 057 (cost rules).
-- Additive and isolated in the `planning` schema — no live screen is touched.
--
--   · planning.payroll_rule     — a store's / HO department's payroll basis for a
--        version/scenario: a monthly basic pay over [start_period,end_period]
--        (optional annual increase), the four chain rates (holiday %, employer
--        pension %, employer NI %, monthly NI threshold) and the four nominals the
--        components post to. Any blank rate falls back to the Assumption Register.
--   · planning.payroll_override — replaces the monthly BASIC for ONE month
--        (headcount / pay changes); the rest of the chain recomputes from it.
--
-- The chain (per month): holiday = basic × holiday%; gross = basic + holiday;
--   pension = gross × pension%; employer NI = max(0, gross − NI threshold) × NI%.
-- The four components each post to plan_line (source PAYROLL); the TOTAL employment
-- cost is carried in each line's lineage (never posted as its own line, so it can't
-- double-count when a P&L template sums the component nominals).
--
-- Idempotent. Safe to re-run.
--
-- ROLLBACK:
--   DROP TABLE IF EXISTS planning.payroll_override;
--   DROP TABLE IF EXISTS planning.payroll_rule;

BEGIN;

CREATE TABLE IF NOT EXISTS planning.payroll_rule (
  rule_id             bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  version_id          bigint NOT NULL REFERENCES planning.plan_version(version_id) ON DELETE CASCADE,
  scenario_code       varchar(30) NOT NULL DEFAULT 'BASE' REFERENCES planning.scenario(scenario_code),
  scope               varchar(24) NOT NULL,          -- COMPANY_STORE / HEAD_OFFICE / FRANCHISE_STORE
  store_code          varchar(40),                   -- NULL for HEAD_OFFICE
  department          varchar(120),                  -- HEAD_OFFICE only
  monthly_basic       numeric(20,6) NOT NULL,        -- basic pay per month
  annual_increase_pct numeric(9,6) NOT NULL DEFAULT 0,
  start_period        char(7) NOT NULL,              -- YYYY-MM
  end_period          char(7) NOT NULL,              -- YYYY-MM
  -- chain rates (NULL → resolve from the Assumption Register)
  holiday_pct         numeric(9,6),                  -- holiday accrual as % of basic
  pension_pct         numeric(9,6),                  -- employer pension as % of gross
  er_ni_pct           numeric(9,6),                  -- employer NI as % of gross above threshold
  ni_threshold_monthly numeric(20,6),                -- monthly employer-NI threshold
  -- component nominals
  nominal_basic       varchar(180) NOT NULL DEFAULT 'ST: Wages & Salaries',
  nominal_holiday     varchar(180) NOT NULL DEFAULT 'ST: Holiday Pay',
  nominal_pension     varchar(180) NOT NULL DEFAULT 'ST: Employer Pension',
  nominal_er_ni       varchar(180) NOT NULL DEFAULT 'ST: Employer NI',
  commentary          text,
  created_by          varchar(120),
  created_at          timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at          timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS ix_payroll_rule_ver ON planning.payroll_rule (version_id, scenario_code, scope, store_code);

CREATE TABLE IF NOT EXISTS planning.payroll_override (
  override_id  bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  rule_id      bigint NOT NULL REFERENCES planning.payroll_rule(rule_id) ON DELETE CASCADE,
  period       char(7) NOT NULL,                     -- YYYY-MM
  monthly_basic numeric(20,6) NOT NULL,              -- overrides basic for this month
  reason       text,
  created_by   varchar(120),
  created_at   timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UNIQUE (rule_id, period)
);

COMMIT;
