-- Migration 059 — Departmental Budgets: zero-based build-up + objective list +
-- the "Departmental Budget Pack" report template.
-- Builds on 049/050/051 (dept budget, workflow, initiatives & cost items).
-- Additive and idempotent — safe to re-run.
--
--   · dept_budget_initiative_cost gains three zero-based columns:
--       driver     — the activity a cost is built from (e.g. "No. of campaigns")
--       quantity   — how many of that activity
--       unit_cost  — cost per activity unit
--     Amount = quantity × unit_cost when both are given (a "flexible" ZBB: a line
--     may still carry a plain lump-sum amount where there is no natural driver).
--   · finance.dept_budget_objective — a shared (global) list of initiative
--     objectives for the create-form dropdown, seeded with the nine standard ones
--     plus "Internal business objective" / "Other"; "+ Add new" appends here.
--   · A seeded report template DEPT_BUDGET_PACK (source adapter `dept_budget`) so a
--     department's budget — summary + zero-based detail — pulls into the Corporate
--     Reporting Centre for SLT sign-off.
--
-- ROLLBACK:
--   ALTER TABLE finance.dept_budget_initiative_cost
--     DROP COLUMN IF EXISTS driver, DROP COLUMN IF EXISTS quantity, DROP COLUMN IF EXISTS unit_cost;
--   DELETE FROM finance.report_template WHERE template_key = 'DEPT_BUDGET_PACK';
--   DROP TABLE IF EXISTS finance.dept_budget_objective;

-- 1) Zero-based build-up columns on the cost item ------------------------------
ALTER TABLE finance.dept_budget_initiative_cost
  ADD COLUMN IF NOT EXISTS driver     varchar(160),
  ADD COLUMN IF NOT EXISTS quantity   numeric(14,4),
  ADD COLUMN IF NOT EXISTS unit_cost  numeric(14,2);

-- 2) Shared objective list -----------------------------------------------------
CREATE TABLE IF NOT EXISTS finance.dept_budget_objective (
  objective_id  bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  label         varchar(160) NOT NULL UNIQUE,
  sort_order    int NOT NULL DEFAULT 100,
  is_seed       boolean NOT NULL DEFAULT false,
  is_active     boolean NOT NULL DEFAULT true,
  created_by    varchar(160),
  created_at    timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP
);

INSERT INTO finance.dept_budget_objective (label, sort_order, is_seed) VALUES
  ('Increase Sales',                1, true),
  ('Increase Margin',               2, true),
  ('Increase Footfall',             3, true),
  ('Increase Conversion',           4, true),
  ('Increase Customer Engagement',  5, true),
  ('Increase Brand Awareness',      6, true),
  ('Increase ECOM Traffic',         7, true),
  ('Internal business objective',   8, true),
  ('Other',                         9, true)
ON CONFLICT (label) DO NOTHING;

-- 3) Departmental Budget Pack report template ----------------------------------
INSERT INTO finance.report_template (template_key, name, purpose, audience, frequency, default_confidentiality, default_ai, effective_date, created_by)
VALUES
  ('DEPT_BUDGET_PACK', 'Departmental Budget Pack',
   'A department''s annual budget for SLT sign-off: target and planned spend, the initiatives and their objectives, and the zero-based cost detail (activity driver × quantity × unit cost) with monthly phasing.',
   'SLT, Finance Director, Department owners.', 'Annual or on submission', 'CONFIDENTIAL',
   '["FINANCE_DIRECTOR","FPA","COMMERCIAL_FINANCE"]'::jsonb, CURRENT_DATE, 'migration 059')
ON CONFLICT (template_key) DO NOTHING;

INSERT INTO finance.report_template_section (template_id, section_key, title, position, mandatory, default_source_key, default_ai_perspective, default_page_type)
SELECT t.template_id, s.section_key, s.title, s.position, s.mandatory, s.src, s.persp, s.ptype
FROM finance.report_template t
CROSS JOIN (VALUES
  ('cover',        'Cover Page',                    1, true,  NULL,          NULL,               'cover'),
  ('summary',      'Departmental Budget Summary',   2, true,  'dept_budget', 'FINANCE_DIRECTOR', 'exec_summary'),
  ('initiatives',  'Initiatives & Objectives',      3, true,  'dept_budget', 'COMMERCIAL_FINANCE','content'),
  ('zbb_detail',   'Zero-Based Cost Detail',        4, true,  'dept_budget', 'FPA',              'content')
) AS s(section_key, title, position, mandatory, src, persp, ptype)
WHERE t.template_key = 'DEPT_BUDGET_PACK'
ON CONFLICT (template_id, section_key) DO NOTHING;
