-- Migration 061 — Planning engine Phase 4: consolidation foundation.
-- Builds on 055–058 (drivers, plan_line, cost/payroll) and 060.
-- Additive and isolated in the `planning` schema — no live screen is touched.
--
-- Two changes:
--  1. plan_line grain gains `department`. Head Office is planned by department, but
--     the result grain did not include it, so two HO departments posting the same
--     nominal in the same month collided on the unique key. The unique index is
--     widened to include department (COALESCE to '' for store scopes where it is
--     NULL), so company-store rows are unchanged and HO rows separate by department.
--  2. planning.consolidation_adjustment — group-level adjustments (intercompany
--     elimination, reclassification, allocation, management adjustment) that feed the
--     Consolidated P&L's Adjustments column. Only APPROVED adjustments consolidate.
--
-- The Consolidated P&L is Σ approved COMPANY_STORE + HEAD_OFFICE + FRANCHISE_STORE
-- plan_line + Σ approved consolidation_adjustment, rendered through the SAME governed
-- pl_format template (scope_kind 'consolidated') — never a separate hard-coded layout.
--
-- Idempotent. Safe to re-run.
--
-- ROLLBACK:
--   DROP TABLE IF EXISTS planning.consolidation_adjustment;
--   DROP INDEX IF EXISTS planning.ux_plan_line_grain;
--   CREATE UNIQUE INDEX ux_plan_line_grain ON planning.plan_line
--     (version_id, scenario_code, scope, COALESCE(store_code,''), nominal, period, source);

BEGIN;

-- 1. Widen the plan_line unique grain to include department.
DROP INDEX IF EXISTS planning.ux_plan_line_grain;
CREATE UNIQUE INDEX IF NOT EXISTS ux_plan_line_grain
  ON planning.plan_line
     (version_id, scenario_code, scope, COALESCE(store_code, ''), COALESCE(department, ''), nominal, period, source);

-- 2. Consolidation adjustments register.
CREATE TABLE IF NOT EXISTS planning.consolidation_adjustment (
  adj_id           bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  version_id       bigint NOT NULL REFERENCES planning.plan_version(version_id) ON DELETE CASCADE,
  scenario_code    varchar(30) NOT NULL DEFAULT 'BASE' REFERENCES planning.scenario(scenario_code),
  kind             varchar(30) NOT NULL DEFAULT 'MANAGEMENT',  -- IC_ELIMINATION / RECLASS / ALLOCATION / MANAGEMENT / OTHER
  nominal          varchar(180) NOT NULL,          -- the P&L account NAME the adjustment posts to
  period           char(7) NOT NULL,               -- YYYY-MM
  amount           numeric(20,6) NOT NULL,         -- signed; added to the consolidated column
  entity_id        bigint,                         -- optional: entity affected
  counterparty_entity_id bigint,                   -- optional: IC counterparty
  reason           text NOT NULL,                  -- documented reason (no unexplained plug)
  status           varchar(12) NOT NULL DEFAULT 'DRAFT',  -- DRAFT / APPROVED
  created_by       varchar(120),
  reviewed_by      varchar(120),
  created_at       timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at       timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT ck_cons_adj_status CHECK (status IN ('DRAFT', 'APPROVED'))
);
CREATE INDEX IF NOT EXISTS ix_cons_adj_ver ON planning.consolidation_adjustment (version_id, scenario_code, status);

COMMIT;
